# ********RoostGPT********

# Test generated by RoostGPT for test test01-api using AI Type Open AI and AI Model gpt-4o
# 
# Test file generated for /employees_get for http method type GET 
# RoostTestHash=ec231a756b
# 
# 

# ********RoostGPT********
# ********RoostGPT********

# Test generated by RoostGPT for test test01-api using AI Type Open AI and AI Model gpt-4o
# 
# Test file generated for /employees_get for http method type GET 
# RoostTestHash=ec231a756b
# 
# 

# ********RoostGPT********
"""
Pytest test file for the /employees endpoint.
Execute with: pytest <test_file_name>.py
"""

import pytest
from pathlib import Path
from validator import SwaggerSchemaValidator

_ENDPOINT = "/employees"
_METHOD = "get"
_TEST_DATA_FILE = "employees.json"
_here = Path(__file__).resolve().parent
_endpoint_data_path = _here / _TEST_DATA_FILE

@pytest.mark.smoke
def test_get_employees(api_client, config, merged_test_data):
    validator = SwaggerSchemaValidator(str(_here / "api.json"))
    data = merged_test_data(_endpoint_data_path)

    for test_case in data:
        search_string = test_case.get("searchString", "")
        expected_status_code = test_case["statusCode"]
        scenario = test_case["scenario"]

        response = api_client.get(
            _ENDPOINT,
            params={"searchString": search_string},
            headers={"Authorization": config.get("api", {}).get("auth_token", "")}
        )

        assert response.status_code == expected_status_code, f"Failed scenario: {scenario}"

        if response.status_code == 200:
            validation_result = validator.validate_schema_by_response(
                _ENDPOINT, _METHOD, str(response.status_code), response
            )
            assert validation_result["valid"], f"Schema validation failed: {validation_result['message']}"

def test_get_employees_invalid_auth(api_client, config):
    response = api_client.get(
        _ENDPOINT,
        headers={"Authorization": "InvalidToken"}
    )
    assert response.status_code == 401, "Expected 401 Unauthorized for invalid auth"

def test_get_employees_missing_auth(api_client):
    response = api_client.get(_ENDPOINT)
    assert response.status_code == 401, "Expected 401 Unauthorized for missing auth"
