# ********RoostGPT********

# Test generated by RoostGPT for test api-testing-pytest-weatherapi using AI Type Open AI and AI Model gpt-5
# 
# Test file generated for /insights/time-series/{project-slug}/workflows/{workflow-name}/jobs_get for http method type GET 
# RoostTestHash=3f5fbf9535
# 
# 

# ********RoostGPT********
"""
Test Suite: Insights Job Timeseries API

Summary:
- Endpoint: GET /insights/time-series/{project-slug}/workflows/{workflow-name}/jobs
- Purpose: Returns timeseries data for all jobs within a workflow.
- Parameters:
  - Path (required): project-slug, workflow-name
  - Query (optional): branch, granularity, start-date, end-date
- Responses:
  - 200: application/json schema with fields: next_page_token (string|null), items (array of objects with name, min_started_at, max_ended_at, timestamp, metrics, etc.)
  - default: Error response with a JSON object containing "message": string
- Security Schemas:
  - API Key via Header: "Circle-Token"
  - API Key via Query: "circle-token"

Notes:
- Authentication tests (invalid/missing tokens) are intentionally skipped here.
- This test suite uses:
  - config.yml via conftest.py to obtain host and auth tokens
  - validator.SwaggerSchemaValidator to validate response schemas against api.json
  - Table-driven tests using the JSON file: insights_time-series_project-slug_workflows_workfl.json

Running:
- Ensure api.json, config.yml, conftest.py, and the JSON data file exist alongside this test module.
- Execute: pytest -q -k "insights_time_series_jobs" or simply pytest -q
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any, Dict, List, Tuple, Optional
from datetime import datetime, timedelta

import pytest

from validator import SwaggerSchemaValidator


# ----------------------------
# Module-level configuration
# ----------------------------

# OpenAPI path as defined in the spec (used by the validator)
_SPEC_PATH = "/insights/time-series/{project-slug}/workflows/{workflow-name}/jobs"
_METHOD = "GET"

# Data file for table-driven tests (same directory as this test file)
TEST_DATA_FILENAME = "insights_time-series_project-slug_workflows_workfl.json"

_here = Path(__file__).resolve().parent
_endpoint_data_path = _here / TEST_DATA_FILENAME


def _load_json_file(path: Path) -> List[Dict[str, Any]]:
    """
    Safely load a JSON array file. Returns [] on failure.
    """
    if not path.exists():
        return []
    try:
        with open(path, "r", encoding="utf-8") as f:
            content = json.load(f)
        if isinstance(content, list):
            return content
        return []
    except Exception:
        return []


def _param_ids(cases: List[Dict[str, Any]]) -> List[str]:
    """
    Build pytest ids for parametrization.
    """
    ids: List[str] = []
    for i, c in enumerate(cases):
        label = c.get("scenario") or f"case-{i+1}"
        status = c.get("statusCode")
        ids.append(f"{label}__{status}")
    return ids


def _merge_required_path_values(
    scenario_case: Dict[str, Any], config_defaults: Dict[str, Any]
) -> Tuple[Optional[str], Optional[str]]:
    """
    Provide required path values (project-slug, workflow-name) using scenario override,
    falling back to config_test_data defaults.
    """
    project_slug = scenario_case.get("project-slug") or config_defaults.get("project-slug")
    workflow_name = scenario_case.get("workflow-name") or config_defaults.get("workflow-name")
    return project_slug, workflow_name


def _build_endpoint_path(project_slug: str, workflow_name: str) -> str:
    """
    Build the runtime endpoint path, preserving reserved characters (like slashes) within project-slug.
    """
    return (
        _SPEC_PATH
        .replace("{project-slug}", project_slug)
        .replace("{workflow-name}", workflow_name)
    )


def _optional_query_from_scenario(scenario_case: Dict[str, Any]) -> Dict[str, Any]:
    """
    Include only optional query parameters if present in the scenario data.
    """
    q: Dict[str, Any] = {}
    if "branch" in scenario_case and scenario_case["branch"] not in (None, ""):
        q["branch"] = scenario_case["branch"]
    if "granularity" in scenario_case and scenario_case["granularity"] not in (None, ""):
        q["granularity"] = scenario_case["granularity"]
    if "start-date" in scenario_case and scenario_case["start-date"] not in (None, ""):
        q["start-date"] = scenario_case["start-date"]
    if "end-date" in scenario_case and scenario_case["end-date"] not in (None, ""):
        q["end-date"] = scenario_case["end-date"]
    return q


def _auth_headers_params(
    token_header_value: str,
    token_query_value: str,
    prefer_header: bool = True,
) -> Tuple[Dict[str, str], Dict[str, Any]]:
    """
    Build auth via header or query param using provided token values.
    prefer_header: try header auth first if token is available.
    Returns (headers, params).
    """
    headers: Dict[str, str] = {}
    params: Dict[str, Any] = {}

    if prefer_header and token_header_value:
        headers["Circle-Token"] = token_header_value
        return headers, params

    if (not prefer_header) and token_query_value:
        params["circle-token"] = token_query_value
        return headers, params

    # Fall back to the other if the preferred is not available
    if token_header_value:
        headers["Circle-Token"] = token_header_value
    elif token_query_value:
        params["circle-token"] = token_query_value

    return headers, params


def _parse_iso8601(s: str) -> Optional[datetime]:
    """
    Parse a limited subset of ISO8601 (e.g., '2024-09-01T00:00:00Z').
    Returns None if parsing fails.
    """
    if not isinstance(s, str) or not s:
        return None
    try:
        if s.endswith("Z"):
            return datetime.strptime(s, "%Y-%m-%dT%H:%M:%SZ")
        # Fallback attempt without trailing Z (rare)
        return datetime.fromisoformat(s)
    except Exception:
        return None


def _format_iso8601(dt: datetime) -> str:
    return dt.strftime("%Y-%m-%dT%H:%M:%SZ")


# Load endpoint test cases at import time to avoid fixture-lazy issues
_ENDPOINT_DATA = _load_json_file(_endpoint_data_path)

# Reusable parametrize args
_PARAM_CASES = _ENDPOINT_DATA
_PARAM_IDS = _param_ids(_ENDPOINT_DATA)

# Initialize validator once for all tests
_VALIDATOR = SwaggerSchemaValidator("api.json")


@pytest.mark.parametrize("scenario_case", _PARAM_CASES, ids=_PARAM_IDS)
@pytest.mark.smoke
def test_insights_time_series_jobs_smoke_required_only_header_auth(
    api_client,
    config_test_data,
    auth_api_key_header,
    auth_api_key_query,
):
    """
    Smoke: Success path using only required parameters (path only),
    authenticating via header if available (or query fallback), validating 200 response schema.
    """
    if not _PARAM_CASES:
        pytest.skip("No ENDPOINT_TEST_DATA found for table-driven tests")

    # Resolve required path params from scenario override + defaults
    project_slug, workflow_name = _merge_required_path_values(scenario_case, config_test_data)
    if not project_slug or not workflow_name:
        pytest.skip("Missing required path params 'project-slug' or 'workflow-name'")

    # Build runtime endpoint path and auth
    runtime_path = _build_endpoint_path(project_slug, workflow_name)

    # Prefer header auth for this smoke test
    headers, auth_params = _auth_headers_params(
        token_header_value=auth_api_key_header or "",
        token_query_value=auth_api_key_query or "",
        prefer_header=True,
    )
    if not headers and not auth_params:
        pytest.skip("No authentication token configured in config.yml for header or query")

    # Request validation: No request body; only path & optional query, so nothing to validate via schema components
    # Proceed with the call
    response = api_client.get(runtime_path, headers=headers, params=auth_params)

    # Assert expected status from scenario
    expected_status = scenario_case.get("statusCode", None)
    if expected_status is None:
        pytest.skip("Scenario missing expected 'statusCode'")

    assert response.status_code == expected_status, f"Unexpected status: {response.status_code}, body={response.text[:500]}"

    # Validate response against OpenAPI spec (200)
    result = _VALIDATOR.validate_schema_by_response(_SPEC_PATH, _METHOD, str(expected_status), response)
    assert result.get("valid"), f"Schema validation failed: {result}"


@pytest.mark.parametrize("scenario_case", _PARAM_CASES, ids=_PARAM_IDS)
def test_insights_time_series_jobs_with_optional_query_params(
    api_client,
    config_test_data,
    auth_api_key_header,
    auth_api_key_query,
):
    """
    Exercise endpoint with optional query params if present in scenario.
    Uses header auth if available, otherwise query auth.
    """
    if not _PARAM_CASES:
        pytest.skip("No ENDPOINT_TEST_DATA found for table-driven tests")

    project_slug, workflow_name = _merge_required_path_values(scenario_case, config_test_data)
    if not project_slug or not workflow_name:
        pytest.skip("Missing required path params 'project-slug' or 'workflow-name'")

    runtime_path = _build_endpoint_path(project_slug, workflow_name)

    optional_params = _optional_query_from_scenario(scenario_case)
    headers, auth_params = _auth_headers_params(
        token_header_value=auth_api_key_header or "",
        token_query_value=auth_api_key_query or "",
        prefer_header=True,
    )
    if not headers and not auth_params:
        pytest.skip("No authentication token configured in config.yml for header or query")

    # Merge auth params with optional query params; avoid overwriting existing keys
    merged_params = dict(auth_params)
    for k, v in optional_params.items():
        if v is not None:
            merged_params[k] = v

    response = api_client.get(runtime_path, headers=headers, params=merged_params)

    expected_status = scenario_case.get("statusCode", None)
    if expected_status is None:
        pytest.skip("Scenario missing expected 'statusCode'")

    assert response.status_code == expected_status, f"Unexpected status: {response.status_code}, body={response.text[:500]}"

    result = _VALIDATOR.validate_schema_by_response(_SPEC_PATH, _METHOD, str(expected_status), response)
    assert result.get("valid"), f"Schema validation failed: {result}"


@pytest.mark.parametrize("scenario_case", _PARAM_CASES, ids=_PARAM_IDS)
def test_insights_time_series_jobs_error_default_invalid_date_window(
    api_client,
    config_test_data,
    auth_api_key_header,
    auth_api_key_query,
):
    """
    Negative/default-case: If start-date and end-date provided by the scenario, create an invalid range
    (end-date earlier than start-date) and assert a non-2xx status. Validate using the 'default' schema.
    """
    if not _PARAM_CASES:
        pytest.skip("No ENDPOINT_TEST_DATA found for table-driven tests")

    project_slug, workflow_name = _merge_required_path_values(scenario_case, config_test_data)
    if not project_slug or not workflow_name:
        pytest.skip("Missing required path params 'project-slug' or 'workflow-name'")

    # Only proceed if scenario provides start-date and end-date to derive an invalid case
    start_s = scenario_case.get("start-date")
    end_s = scenario_case.get("end-date")
    if not start_s or not end_s:
        pytest.skip("Scenario lacks both 'start-date' and 'end-date'; skipping invalid date window test")

    start_dt = _parse_iso8601(start_s)
    end_dt = _parse_iso8601(end_s)
    if not start_dt or not end_dt:
        pytest.skip("Unable to parse ISO8601 dates from scenario; skipping invalid date window test")

    # Build invalid range: end-date strictly before start-date
    invalid_end = start_dt - timedelta(days=1)
    invalid_end_s = _format_iso8601(invalid_end)

    runtime_path = _build_endpoint_path(project_slug, workflow_name)

    headers, auth_params = _auth_headers_params(
        token_header_value=auth_api_key_header or "",
        token_query_value=auth_api_key_query or "",
        prefer_header=True,
    )
    if not headers and not auth_params:
        pytest.skip("No authentication token configured in config.yml for header or query")

    # Start with scenario optional params, then override end-date with invalid
    q = _optional_query_from_scenario(scenario_case)
    q["end-date"] = invalid_end_s
    q["start-date"] = start_s  # keep start-date unchanged
    for k, v in auth_params.items():
        q.setdefault(k, v)

    response = api_client.get(runtime_path, headers=headers, params=q)

    # Expect default error (non-2xx) per spec since only 200 and default are provided
    assert not (200 <= response.status_code < 300), f"Expected non-2xx for invalid date window, got {response.status_code}"

    # Validate using 'default' response schema
    result = _VALIDATOR.validate_schema_by_response(_SPEC_PATH, _METHOD, "default", response)
    assert result.get("valid"), f"Default error schema validation failed: {result}"


@pytest.mark.parametrize("scenario_case", _PARAM_CASES, ids=_PARAM_IDS)
def test_insights_time_series_jobs_query_auth_path(
    api_client,
    config_test_data,
    auth_api_key_header,
    auth_api_key_query,
):
    """
    Exercise query-based API key authentication path if configured.
    This is not an authentication test; it ensures endpoint functions with query token.
    """
    if not _PARAM_CASES:
        pytest.skip("No ENDPOINT_TEST_DATA found for table-driven tests")

    if not (auth_api_key_query or ""):
        pytest.skip("No query token configured; skipping query-auth path test")

    project_slug, workflow_name = _merge_required_path_values(scenario_case, config_test_data)
    if not project_slug or not workflow_name:
        pytest.skip("Missing required path params 'project-slug' or 'workflow-name'")

    runtime_path = _build_endpoint_path(project_slug, workflow_name)

    # Prefer query auth in this scenario
    headers, auth_params = _auth_headers_params(
        token_header_value=auth_api_key_header or "",
        token_query_value=auth_api_key_query or "",
        prefer_header=False,
    )
    if not headers and not auth_params:
        pytest.skip("No authentication token configured in config.yml for header or query")

    # Include optional params if present in scenario
    q = _optional_query_from_scenario(scenario_case)
    for k, v in auth_params.items():
        q.setdefault(k, v)

    response = api_client.get(runtime_path, headers=headers, params=q)

    expected_status = scenario_case.get("statusCode", None)
    if expected_status is None:
        pytest.skip("Scenario missing expected 'statusCode'")

    assert response.status_code == expected_status, f"Unexpected status: {response.status_code}, body={response.text[:500]}"

    result = _VALIDATOR.validate_schema_by_response(_SPEC_PATH, _METHOD, str(expected_status), response)
    assert result.get("valid"), f"Schema validation failed: {result}"
