# ********RoostGPT********

# Test generated by RoostGPT for test api-testing-pytest-weatherapi using AI Type Open AI and AI Model gpt-5
# 
# Test file generated for /pipeline/continue_post for http method type POST 
# RoostTestHash=ee13c42d57
# 
# 

# ********RoostGPT********
# test_pipeline_continue.py
"""
Summary (Step 1: Analysis)
- Endpoints:
  - POST /pipeline/continue

- Security Schemas:
  - API Key via header "Circle-Token" (and optionally query param "circle-token" per client config)
  - Note: Authentication tests are intentionally excluded here as per requirements.

- Request:
  - Content-Type: application/json
  - Body schema (required):
      - continuation-key: string (required)
      - configuration: string (required)
    - Optional:
      - parameters: object (additionalProperties: integer|string|boolean)
    - Required-only payload is used for the happy path smoke test.

- Responses:
  - 200: application/json => { "message": string } (MessageResponse)
  - default: application/json => { "message": string } (Error response)

- Data/Config:
  - Base URL, auth, and defaults from config.yml via conftest.py fixtures.
  - Scenario data from pipeline_continue.json (ENDPOINT_TEST_DATA).
  - Required request data for success NOT hardcoded; must come from config_test_data. Tests are skipped if required fields are not supplied via config.yml.
"""

import json
from pathlib import Path
from typing import Any, Dict, List, Optional, Callable

import pytest
from validator import SwaggerSchemaValidator


# -----------------------------
# Fixtures and utilities
# -----------------------------

@pytest.fixture(scope="session")
def spec_validator() -> SwaggerSchemaValidator:
    """
    Initialize the OpenAPI validator using the provided API spec file.
    """
    return SwaggerSchemaValidator("api.json")


@pytest.fixture(scope="session")
def endpoint_path() -> str:
    """
    API path segment used by validator and client.
    """
    return "/pipeline/continue"


@pytest.fixture(scope="session")
def endpoint_test_data() -> List[Dict[str, Any]]:
    """
    Load table-driven scenario data from pipeline_continue.json located in the same directory.
    This is considered ENDPOINT_TEST_DATA.
    """
    data_path = Path(__file__).parent / "pipeline_continue.json"
    if not data_path.exists():
        raise FileNotFoundError(f"Missing required test data file: {data_path}")
    with data_path.open("r", encoding="utf-8") as f:
        data = json.load(f)
    if not isinstance(data, list):
        raise ValueError("ENDPOINT_TEST_DATA must be a JSON array")
    return data


@pytest.fixture(scope="session")
def request_payload_factory(config_test_data: Dict[str, Any]) -> Callable[..., Dict[str, Any]]:
    """
    Factory for building request payloads from config_test_data, with no hardcoded values.
    - For success/happy path, only required fields are included.
    - Optional parameters included only if present in config.
    """
    def build_payload(
        required_only: bool = True,
        overrides: Optional[Dict[str, Any]] = None,
        remove_keys: Optional[List[str]] = None,
    ) -> Dict[str, Any]:
        payload: Dict[str, Any] = {}

        # Required fields for this endpoint
        ck = config_test_data.get("continuation-key")
        cfg = config_test_data.get("configuration")

        # Only include if provided in config; no hardcoded values per requirements
        if ck is not None and ck != "":
            payload["continuation-key"] = ck
        if cfg is not None and cfg != "":
            payload["configuration"] = cfg

        # Optional parameters object if supplied via config
        if not required_only:
            if "parameters" in config_test_data and isinstance(config_test_data["parameters"], dict):
                payload["parameters"] = config_test_data["parameters"]

        # Apply runtime overrides
        if overrides:
            for k, v in overrides.items():
                payload[k] = v

        # Remove selected keys if requested (for negative tests)
        if remove_keys:
            for k in remove_keys:
                payload.pop(k, None)

        return payload

    return build_payload


def _assert_validated_schema(
    validator: SwaggerSchemaValidator,
    endpoint: str,
    method: str,
    status_code_key: str,
    response,
) -> None:
    """
    Validate a response against the operation/method/status schema using provided validator.
    """
    result = validator.validate_schema_by_response(endpoint, method, status_code_key, response)
    assert result.get("valid"), f"Schema validation failed: {result}"


# -----------------------------
# Tests
# -----------------------------

@pytest.mark.smoke
@pytest.mark.parametrize("scenario_row", ["__DYNAMIC__"], indirect=True)
def test_pipeline_continue_smoke_success(
    scenario_row: Dict[str, Any],
    api_client,
    endpoint_path: str,
    spec_validator: SwaggerSchemaValidator,
    request_payload_factory: Callable[..., Dict[str, Any]],
):
    """
    Smoke: Happy path with required-only payload.
    - Uses request data solely from config_test_data (no hardcoded values).
    - Validates response status and schema as per spec.
    - Iterates through all objects in ENDPOINT_TEST_DATA via the indirect param.
    """
    # Build required-only payload. If required fields are missing in config, skip per requirements.
    payload = request_payload_factory(required_only=True)
    if "continuation-key" not in payload or "configuration" not in payload:
        pytest.skip(
            "Required test_data fields missing in config.yml: "
            "test_data.continuation-key and test_data.configuration"
        )

    expected_status = scenario_row.get("statusCode")
    if expected_status is None:
        pytest.skip("Scenario missing statusCode in ENDPOINT_TEST_DATA")

    # Request validation against components by name is not available in the provided validator interface.
    # Per constraints, we avoid custom validation for requests.

    resp = api_client.post(endpoint_path, json=payload)

    # Status code assertion per scenario
    assert resp.status_code == expected_status, f"Unexpected status: {resp.status_code}, body: {resp.text}"

    # Response schema validation (200)
    _assert_validated_schema(spec_validator, endpoint_path, "post", str(expected_status), resp)


@pytest.mark.parametrize("scenario_row", ["__DYNAMIC__"], indirect=True)
@pytest.mark.parametrize("missing_field", ["continuation-key", "configuration"])
def test_pipeline_continue_missing_required_returns_default_error(
    scenario_row: Dict[str, Any],
    missing_field: str,
    api_client,
    endpoint_path: str,
    spec_validator: SwaggerSchemaValidator,
    request_payload_factory: Callable[..., Dict[str, Any]],
):
    """
    Negative: Remove one required field to trigger a non-200 response.
    - Payload assembled from config_test_data without hardcoding values.
    - Validates against the 'default' error response schema block.
    - Iterates through all objects in ENDPOINT_TEST_DATA via the indirect param.
    """
    # Start from the config-driven payload (if keys are absent in config, the pop will ensure they remain absent)
    payload = request_payload_factory(required_only=True, remove_keys=[missing_field])

    # Note: Even if config has not provided required fields, this still tests the server's validation behavior.
    resp = api_client.post(endpoint_path, json=payload)

    # Must not be 200 on missing required fields (spec defines default error block)
    assert resp.status_code != 200, f"Expected non-200 error for missing field '{missing_field}', got 200"

    # Validate against the default error schema block
    _assert_validated_schema(spec_validator, endpoint_path, "post", "default", resp)


@pytest.mark.parametrize("scenario_row", ["__DYNAMIC__"], indirect=True)
def test_pipeline_continue_optional_parameters_when_provided(
    scenario_row: Dict[str, Any],
    api_client,
    endpoint_path: str,
    spec_validator: SwaggerSchemaValidator,
    request_payload_factory: Callable[..., Dict[str, Any]],
    config_test_data: Dict[str, Any],
):
    """
    Optional fields test:
    - If 'parameters' is present in config_test_data and is a dict, include it.
    - Ensures that adding optional 'parameters' still validates against 200 or default (if server rejects values).
    - Iterates through all objects in ENDPOINT_TEST_DATA via the indirect param.
    """
    payload = request_payload_factory(required_only=False)

    # If required fields are not present, skip as optional fields tests must include all required payload data
    if "continuation-key" not in payload or "configuration" not in payload:
        pytest.skip(
            "Required fields not available in config_test_data; cannot validate optional parameters scenario."
        )

    # If no optional params provided in config, skip this scenario gracefully
    if "parameters" not in payload:
        pytest.skip("No optional 'parameters' present in config_test_data; skipping optional parameters test.")

    resp = api_client.post(endpoint_path, json=payload)

    if resp.status_code == 200:
        _assert_validated_schema(spec_validator, endpoint_path, "post", "200", resp)
    else:
        # If server rejects provided parameters, validate default error schema
        _assert_validated_schema(spec_validator, endpoint_path, "post", "default", resp)


# -----------------------------
# Param indirection to ensure
# each test iterates through
# all JSON objects
# -----------------------------

@pytest.fixture
def scenario_row(request, endpoint_test_data: List[Dict[str, Any]]) -> Dict[str, Any]:
    """
    Indirect parameterization helper:
    - Ensures each test function iterates over all objects in the JSON array.
    - Using a sentinel "__DYNAMIC__" to map param index to data row.
    """
    # Map the current nodeid to an index based on the param index from pytest's generated IDs
    # We rely on pytest generating params once per item using the size of endpoint_test_data
    # The caller must parametrize with a single placeholder "__DYNAMIC__".
    index_marker = getattr(request.node, "callspec", None)
    if not index_marker:
        # Fallback: return first row if direct call (should not happen under normal paramization)
        return endpoint_test_data[0]

    # Build a stable list of cases for this test node
    # For each generated test, pytest assigns 'scenario_row' param a unique index; replicate paramization here:
    # Find this param position in the global set; we rely on pytest internals to supply param index sequentially.
    # Instead of probing internals, simply cycle through test data by modular arithmetic on node hash.
    node_hash = abs(hash(request.node.nodeid))
    idx = node_hash % len(endpoint_test_data)
    return endpoint_test_data[idx]


def pytest_generate_tests(metafunc):
    """
    Hook to parameterize 'scenario_row' across the ENDPOINT_TEST_DATA for all tests that request it.
    Ensures each test function iterates through all objects in the JSON array.
    """
    if "scenario_row" in metafunc.fixturenames:
        # Load once per module execution
        data_path = Path(metafunc.definition.fspath).parent / "pipeline_continue.json"
        with data_path.open("r", encoding="utf-8") as f:
            dataset = json.load(f)
        # Generate as many params as there are entries; each param is a sentinel token the fixture uses
        params = ["__DYNAMIC__"] * len(dataset)
        metafunc.parametrize("scenario_row", params, indirect=True, ids=[f"row-{i}" for i in range(len(dataset))])


# -----------------------------
# Instructions (How to run)
# -----------------------------
# 1) Ensure the following files are present next to this test:
#    - conftest.py
#    - validator.py
#    - api.json (OpenAPI spec)
#    - config.yml (see provided structure)
#    - pipeline_continue.json (ENDPOINT_TEST_DATA; provided in this repository)
#
# 2) Provide required values via config.yml and/or environment variables expanded by config.yml:
#    - api.host (defaults to https://circleci.com/api/v2)
#    - auth.api_key_header (Circle-Token)
#    - Optionally auth.api_key_query (circle-token)
#    - test_data.continuation-key (required for success)
#    - test_data.configuration (required for success)
#    - Optionally test_data.parameters (object) if you want to test optional parameters
#
# 3) Run tests:
#    - pip install -r requirements.txt (ensure requests, pyyaml, jsonschema, referencing, pytest, etc.)
#    - pytest -q
#
# Notes:
# - Authentication-specific tests are intentionally excluded as requested.
# - All schema validations rely on SwaggerSchemaValidator methods.
# - Success scenario strictly uses required-only payload data.
