# ********RoostGPT********

# Test generated by RoostGPT for test api-testing-pytest-weatherapi using AI Type Open AI and AI Model gpt-5
# 
# Test file generated for /insights/{project-slug}/workflows/{workflow-name}/test-metrics_get for http method type GET 
# RoostTestHash=4d63ad4d9a
# 
# 

# ********RoostGPT********
# Summary of API under test
# 
# Endpoints:
# - GET /insights/{project-slug}/workflows/{workflow-name}/test-metrics
#
# Security Schemas:
# - API Key via header: "Circle-Token" (handled via conftest.py auth + APIClient)
# - API Key via query: "circle-token" (handled via conftest.py auth + APIClient)
#
# Parameters:
# - Path (required): project-slug (string), workflow-name (string)
# - Query (optional): branch (string), all-branches (boolean)
#
# Responses:
# - 200: application/json with schema for test metrics (as defined inline in the OpenAPI path)
# - default: application/json { message: string } for error responses
#
# Notes:
# - Authentication tests are intentionally skipped here (covered by dedicated test_authentication.py).
# - Success scenarios are table-driven from insights_project-slug_workflows_workflow-name_test.json.
# - Request/response schema validations use SwaggerSchemaValidator (api.json).
