# ********RoostGPT********

# Test generated by RoostGPT for test api-testing-pytest-weatherapi using AI Type Open AI and AI Model gpt-5
# 
# Test file generated for /project/{project-slug}/checkout-key_post for http method type POST 
# RoostTestHash=6516866958
# 
# 

# ********RoostGPT********
"""
Pytest suite for: POST /project/{project-slug}/checkout-key

Summary (Step 1: Analysis)
- Endpoints:
  - POST /project/{project-slug}/checkout-key
- Security Schemas:
  - API Key via HTTP header: "Circle-Token" (config key: auth.api_key_header)
  - API Key via query param: "circle-token" (config key: auth.api_key_query)
- Parameters:
  - Path: project-slug (string, required, allowReserved: true)
- Request Body:
  - application/json -> schema: CheckoutKeyInput
    - properties:
      - type (string) — required; allowed by description: "deploy-key" or "user-key"
- Response:
  - 201 application/json -> schema: CheckoutKey (object)
    - required: public-key, type, fingerprint, preferred, created-at
  - default application/json -> schema: { message: string }
- Notes:
  - Only usable with a user API token; requires prior GitHub authorization per spec.
  - This test suite validates:
    - Request payload against components schema CheckoutKeyInput before sending
    - Response payload against spec using validate_schema_by_response
    - Path parameter handling including URL-escaped project-slug
    - Multiple scenarios from ENDPOINT_TEST_DATA loaded from project_project-slug_checkout-key.json
  - Authentication coverage is intentionally skipped here as per instructions.

How to run:
- Ensure files present: conftest.py, config.yml, api.json, project_project-slug_checkout-key.json
- Provide API host and credentials via config.yml and referenced environment variables
- Run: pytest -q
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any, Dict, Iterable, List, Mapping, Optional
from urllib.parse import quote

import pytest

from validator import SwaggerSchemaValidator


# -------------------------------
# Configuration and data loading
# -------------------------------

TEST_DATA_FILENAME = "project_project-slug_checkout-key.json"
_API_SPEC_FILENAME = "api.json"
_SPEC_PATH = str((Path(__file__).resolve().parent / _API_SPEC_FILENAME))

_ENDPOINT_TEMPLATE = "/project/{project-slug}/checkout-key"
_ALLOWED_SUCCESS = {"201"}  # strictly from API spec

# Load endpoint table-driven data eagerly, outside of pytest fixtures
def _load_json_file(p: Path) -> Any:
    if not p.exists():
        raise pytest.UsageError(f"Test data file not found: {p}")
    try:
        with p.open("r", encoding="utf-8") as f:
            return json.load(f)
    except json.JSONDecodeError as e:
        raise pytest.UsageError(f"Failed to parse JSON file at {p}: {e}") from e


def _param_ids(cases: Iterable[Mapping[str, Any]]) -> List[str]:
    ids: List[str] = []
    for i, c in enumerate(cases):
        label = c.get("scenario") or c.get("name") or c.get("project-slug") or f"case-{i}"
        ids.append(str(label))
    return ids


_here = Path(__file__).resolve().parent
_endpoint_data_path = _here / TEST_DATA_FILENAME
try:
    _ENDPOINT_DATA = _load_json_file(_endpoint_data_path)
except pytest.UsageError:
    # Fallback to empty list to avoid import-time crash; tests will xfail/skip if no data.
    _ENDPOINT_DATA = []

_PARAM_CASES = list(_ENDPOINT_DATA) if isinstance(_ENDPOINT_DATA, list) else []
_PARAM_IDS = _param_ids(_PARAM_CASES)


# -------------------------------
# Helpers
# -------------------------------

def _merge_test_data(base: Mapping[str, Any], override: Mapping[str, Any]) -> Dict[str, Any]:
    """
    Merge base config test_data with scenario override. Shallow merge only.
    Scenario keys win over base keys.
    """
    merged = dict(base or {})
    merged.update(dict(override or {}))
    return merged


def _build_endpoint_path(project_slug: str, *, url_escape: bool = False) -> str:
    """
    Construct the endpoint path, optionally URL-escaping the project-slug segment.
    Important: for schema validation we must use the templated path (_ENDPOINT_TEMPLATE).
    """
    slug = quote(project_slug, safe="") if url_escape else project_slug
    return _ENDPOINT_TEMPLATE.replace("{project-slug}", slug)


def _build_auth_headers_and_params(api_key_header_value: str, api_key_query_value: str) -> (Dict[str, str], Dict[str, str]):
    """
    Compose auth via header and/or query parameter using configured values.
    Header key: Circle-Token
    Query key: circle-token
    """
    headers: Dict[str, str] = {}
    params: Dict[str, str] = {}
    if (api_key_header_value or "").strip():
        headers["Circle-Token"] = api_key_header_value.strip()
    if (api_key_query_value or "").strip():
        params["circle-token"] = api_key_query_value.strip()
    return headers, params


def _validate_request_body_or_skip(validator: SwaggerSchemaValidator, body: Dict[str, Any], schema_name: str) -> None:
    """
    Validate request payload using validator.validate_json if available.
    If the method is unavailable in the validator, skip preflight validation for this test.
    """
    validate_fn = getattr(validator, "validate_json", None)
    if callable(validate_fn):
        result = validate_fn(body, schema_name)
        # Expect a dict-like result with "valid" boolean.
        if isinstance(result, dict) and not result.get("valid", False):
            pytest.fail(f"Request body failed schema validation for {schema_name}: {result}")
    else:
        pytest.skip("Request schema validation not available (validate_json missing in SwaggerSchemaValidator)")


def _validate_response_schema(validator: SwaggerSchemaValidator, response, *, method: str) -> Dict[str, Any]:
    """
    Validate response against the spec using validate_schema_by_response.
    Attempts exact status block; if not present, falls back to 'default'.
    """
    status_str = str(getattr(response, "status_code", ""))
    res = validator.validate_schema_by_response(_ENDPOINT_TEMPLATE, method, status_str, response)
    if isinstance(res, dict) and not res.get("valid", False):
        # If there is no explicit response block for this status code, try default
        if "No response block for" in res.get("message", ""):
            res_default = validator.validate_schema_by_response(_ENDPOINT_TEMPLATE, method, "default", response)
            return res_default
    return res


# -------------------------------
# Fixtures
# -------------------------------

@pytest.fixture(scope="module")
def schema_validator() -> SwaggerSchemaValidator:
    """
    Initialize the OpenAPI schema validator for api.json.
    """
    return SwaggerSchemaValidator(_SPEC_PATH)


@pytest.fixture(scope="module")
def endpoint_template() -> str:
    return _ENDPOINT_TEMPLATE


@pytest.fixture(scope="function")
def make_payload():
    """
    Factory for request payloads. Only builds payloads using provided data without hardcoding values.
    """
    def _builder(effective_data: Mapping[str, Any], *, include_required_only: bool = True) -> Dict[str, Any]:
        # Required field: type
        payload: Dict[str, Any] = {}
        t = effective_data.get("type")
        if t is not None:
            payload["type"] = t
        elif include_required_only:
            # When required 'type' is missing in provided test data and we're asked to include only required fields,
            # we simply do not include it and let pre-validation or API error handle it.
            # This adheres to "do not hardcode" and uses only provided test/config data.
            pass
        else:
            # Optional mode for future expansion; still do not hardcode additional keys/values.
            pass
        return payload
    return _builder


# -------------------------------
# Tests
# -------------------------------

class TestCreateCheckoutKey:
    """
    Tests for POST /project/{project-slug}/checkout-key

    Notes:
    - Authentication negative/variation tests are skipped here by design.
    - Happy-path uses only required payload fields (type) if provided by config_test_data or scenario.
    - Table-driven scenarios loaded from project_project-slug_checkout-key.json
    """

    @pytest.mark.smoke
    @pytest.mark.parametrize("scenario_case", _PARAM_CASES, ids=_PARAM_IDS)
    def test_create_checkout_key_smoke_success(
        self,
        scenario_case: Mapping[str, Any],
        api_client,
        auth_api_key_header: str,
        auth_api_key_query: str,
        config_test_data: Mapping[str, Any],
        schema_validator: SwaggerSchemaValidator,
        make_payload,
        endpoint_template: str,
    ):
        """
        Smoke: Create checkout key with only required payload fields.
        - Uses project-slug from scenario override, else config.
        - Validates request body against CheckoutKeyInput before send.
        - On 201: validates against CheckoutKey schema via response validation helper.
        - On non-2xx: validates against 'default' error response schema.
        """
        if not _PARAM_CASES:
            pytest.skip(f"No endpoint data found in {TEST_DATA_FILENAME}")

        # Merge default config test data with scenario overrides
        effective = _merge_test_data(config_test_data, scenario_case)

        project_slug = (effective.get("project-slug") or "").strip()
        if not project_slug:
            pytest.skip("Missing required path parameter: project-slug (from config_test_data or scenario)")

        headers, params = _build_auth_headers_and_params(auth_api_key_header, auth_api_key_query)
        if not headers and not params:
            pytest.skip("No authentication provided via fixtures; skipping until auth is configured")

        # Build payload with only required fields (no hardcoded values)
        payload = make_payload(effective, include_required_only=True)

        # Must include 'type' for happy-path; if not provided in data, skip
        if "type" not in payload:
            pytest.skip("Required request field 'type' not provided by config_test_data/scenario for smoke test")

        # Validate request against schema (CheckoutKeyInput)
        _validate_request_body_or_skip(schema_validator, payload, "CheckoutKeyInput")

        endpoint_path = _build_endpoint_path(project_slug, url_escape=False)
        response = api_client.post(
            endpoint_path,
            headers=headers,
            params=params,
            json=payload,
        )

        # Validate response schema; prefer exact status, fallback to default if not defined
        validation = _validate_response_schema(schema_validator, response, method="POST")
        assert validation.get("valid", False), f"Response schema validation failed: {validation}"

        # Assert according to spec's defined success codes
        if 200 <= response.status_code < 300:
            assert str(response.status_code) in _ALLOWED_SUCCESS, (
                f"Unexpected success status code {response.status_code}; expected one of: {_ALLOWED_SUCCESS}"
            )
        else:
            # default block present => ensure not 2xx
            assert not (200 <= response.status_code < 300), "Error response must not be 2xx per default response rule"

    @pytest.mark.parametrize("scenario_case", _PARAM_CASES, ids=_PARAM_IDS)
    def test_create_checkout_key_missing_type_triggers_default_error(
        self,
        scenario_case: Mapping[str, Any],
        api_client,
        auth_api_key_header: str,
        auth_api_key_query: str,
        config_test_data: Mapping[str, Any],
        schema_validator: SwaggerSchemaValidator,
        make_payload,
        endpoint_template: str,
    ):
        """
        Negative: Missing required body field 'type' should produce a non-2xx response conforming to 'default' schema.
        Only runs when 'type' is NOT provided by either config_test_data or scenario override.
        """
        if not _PARAM_CASES:
            pytest.skip(f"No endpoint data found in {TEST_DATA_FILENAME}")

        effective = _merge_test_data(config_test_data, scenario_case)

        # If any data provides 'type', this negative case is not applicable for that scenario.
        if effective.get("type") is not None:
            pytest.skip("Scenario/config provides 'type'; skipping missing-type negative case for this scenario")

        project_slug = (effective.get("project-slug") or "").strip()
        if not project_slug:
            pytest.skip("Missing required path parameter: project-slug (from config_test_data or scenario)")

        headers, params = _build_auth_headers_and_params(auth_api_key_header, auth_api_key_query)
        if not headers and not params:
            pytest.skip("No authentication provided via fixtures; skipping until auth is configured")

        payload = make_payload(effective, include_required_only=True)
        # Intentionally do not add 'type'

        # Pre-validation should fail if validate_json is available; if it passes or not available, continue to call API.
        try:
            _validate_request_body_or_skip(schema_validator, payload, "CheckoutKeyInput")
            # If validation did not fail, proceed — server may still reject.
        except AssertionError:
            # Expected to fail preflight; continue to send request to assert default error contract.
            pass
        except pytest.SkipTest:
            # If validate_json unavailable, proceed with API call-based validation.
            pass

        endpoint_path = _build_endpoint_path(project_slug, url_escape=False)
        response = api_client.post(
            endpoint_path,
            headers=headers,
            params=params,
            json=payload,
        )

        # Expect non-2xx; validate via default
        assert not (200 <= response.status_code < 300), "Expected non-2xx when 'type' is missing"
        validation = _validate_response_schema(schema_validator, response, method="POST")
        assert validation.get("valid", False), f"Default error response schema validation failed: {validation}"

    @pytest.mark.parametrize("scenario_case", _PARAM_CASES, ids=_PARAM_IDS)
    def test_create_checkout_key_with_url_escaped_project_slug(
        self,
        scenario_case: Mapping[str, Any],
        api_client,
        auth_api_key_header: str,
        auth_api_key_query: str,
        config_test_data: Mapping[str, Any],
        schema_validator: SwaggerSchemaValidator,
        make_payload,
        endpoint_template: str,
    ):
        """
        Validate support for URL-escaped project-slug as permitted by the spec (allowReserved: true).
        Runs only if required inputs are provided by data.
        """
        if not _PARAM_CASES:
            pytest.skip(f"No endpoint data found in {TEST_DATA_FILENAME}")

        effective = _merge_test_data(config_test_data, scenario_case)

        project_slug = (effective.get("project-slug") or "").strip()
        if not project_slug:
            pytest.skip("Missing required path parameter: project-slug (from config_test_data or scenario)")

        headers, params = _build_auth_headers_and_params(auth_api_key_header, auth_api_key_query)
        if not headers and not params:
            pytest.skip("No authentication provided via fixtures; skipping until auth is configured")

        payload = make_payload(effective, include_required_only=True)
        if "type" not in payload:
            pytest.skip("Required request field 'type' not provided; skipping URL-escaped slug scenario")

        _validate_request_body_or_skip(schema_validator, payload, "CheckoutKeyInput")

        endpoint_path = _build_endpoint_path(project_slug, url_escape=True)
        response = api_client.post(
            endpoint_path,
            headers=headers,
            params=params,
            json=payload,
        )

        validation = _validate_response_schema(schema_validator, response, method="POST")
        assert validation.get("valid", False), f"Response schema validation failed (URL-escaped slug): {validation}"

        if 200 <= response.status_code < 300:
            assert str(response.status_code) in _ALLOWED_SUCCESS, (
                f"Unexpected success status code {response.status_code}; expected one of: {_ALLOWED_SUCCESS}"
            )
        else:
            assert not (200 <= response.status_code < 300), "Error response must not be 2xx per default response rule"

    @pytest.mark.parametrize("scenario_case", _PARAM_CASES, ids=_PARAM_IDS)
    def test_security_schemas_variations_skipped(
        self,
        scenario_case: Mapping[str, Any],
    ):
        """
        Security schema coverage (invalid/missing/expired tokens) must be tested in a dedicated authentication test file.
        Skipping here per instructions.
        """
        pytest.skip("Authentication variation tests are handled in dedicated test_authentication.py")
