# ********RoostGPT********

# Test generated by RoostGPT for test api-testing-pytest-weatherapi using AI Type Open AI and AI Model gpt-5
# 
# Test file generated for /pipeline_get for http method type GET 
# RoostTestHash=2a8f9b2e24
# 
# 

# ********RoostGPT********
# test_pipeline.py
"""
Summary of Identified Endpoints and Security Schemas

Endpoints:
- GET /pipeline
  - Summary: Get a list of pipelines.
  - Query parameters (all optional):
    - org-slug: string
    - page-token: string (allowEmptyValue: true)
    - mine: boolean
  - Responses:
    - 200: application/json schema: PipelineListResponse (items[], next_page_token)
    - default: application/json schema: { message: string }

Security:
- API key supported via:
  - Header: "Circle-Token" (configured via config.yml -> auth.api_key_header)
  - Query: "circle-token" (configured via config.yml -> auth.api_key_query)
- Authentication is handled by fixtures defined in conftest.py (APIClient).
- Per instruction, authentication-specific tests are covered elsewhere and are not included here.
"""

from pathlib import Path
from typing import Any, Dict, Iterable, List, Tuple

import json
import pytest

from validator import SwaggerSchemaValidator


# ----------------------------
# Fixtures and Helpers
# ----------------------------

@pytest.fixture(scope="session")
def api_spec_path() -> str:
    """
    Returns the path to the OpenAPI spec used for validation.
    """
    return str(Path(__file__).with_name("api.json"))


@pytest.fixture(scope="session")
def swagger_validator(api_spec_path: str) -> SwaggerSchemaValidator:
    """
    Provides a SwaggerSchemaValidator initialized with the provided spec.
    """
    return SwaggerSchemaValidator(api_spec_path)


@pytest.fixture(scope="session")
def endpoint_path() -> str:
    return "/pipeline"


@pytest.fixture(scope="session")
def http_method() -> str:
    return "get"


@pytest.fixture(scope="session")
def endpoint_test_data() -> List[Dict[str, Any]]:
    """
    Loads table-driven ENDPOINT_TEST_DATA from pipeline.json in the same directory.

    The file is expected to be a JSON array of objects, each containing scenario-specific
    fields for query parameters and expected statusCode.
    """
    data_path = Path(__file__).with_name("pipeline.json")
    with data_path.open("r", encoding="utf-8") as f:
        data = json.load(f)
    if not isinstance(data, list):
        raise ValueError("pipeline.json must contain a JSON array")
    return data


@pytest.fixture(scope="session")
def merged_scenarios(config_test_data: Dict[str, Any], endpoint_test_data: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
    """
    Merge default test_data from config.yml with scenario-specific ENDPOINT_TEST_DATA.
    Scenario values override defaults. Only recognized query params are emitted.
    """
    recognized_params = {"org-slug", "page-token", "mine"}
    scenarios: List[Dict[str, Any]] = []

    for case in endpoint_test_data:
        merged: Dict[str, Any] = {}
        # Start with defaults from config for only recognized params if provided and non-empty
        for k in recognized_params:
            v = config_test_data.get(k)
            if v not in (None, ""):
                merged[k] = v
        # Override with scenario-specific values
        for k, v in case.items():
            if k in recognized_params:
                merged[k] = v

        # Carry through meta info such as expected statusCode and scenario description
        result = {
            "params": merged,
            "expected_status": case.get("statusCode"),
            "scenario": case.get("scenario", ""),
        }
        scenarios.append(result)

    return scenarios


def _assert_validated_response(
    swagger_validator: SwaggerSchemaValidator,
    endpoint: str,
    method: str,
    expected_status_key: str,
    response
) -> None:
    """
    Validate response body against the OpenAPI schema for the given endpoint/method/status code key.
    expected_status_key should be '200' for success, and 'default' for error cases.
    """
    validation = swagger_validator.validate_schema_by_response(endpoint, method, expected_status_key, response)
    assert validation.get("valid") is True, f"Schema validation failed for {endpoint} {method.upper()} {expected_status_key}: {validation}"


def _extract_json(response) -> Dict[str, Any]:
    try:
        return response.json()
    except Exception:
        return {}


# ----------------------------
# Tests
# ----------------------------

@pytest.mark.smoke
def test_list_pipelines_smoke_success(
    api_client,
    swagger_validator: SwaggerSchemaValidator,
    endpoint_path: str,
    http_method: str,
    merged_scenarios: List[Dict[str, Any]],
):
    """
    Smoke test: Validate successful 200 responses for GET /pipeline using only required inputs
    (no required params exist; scenarios provide optional params from pipeline.json/config).
    - Asserts HTTP 200
    - Validates schema for success using the OpenAPI spec
    - Ensures JSON content type for success responses
    """
    for sc in merged_scenarios:
        expected_status = sc.get("expected_status")
        if expected_status != 200:
            # Skip non-200 scenarios in the smoke test
            continue

        params = sc.get("params") or {}

        # Note: Request pre-validation is skipped because the provided validator
        # does not expose a request-parameter validator function and the spec
        # does not define dedicated component schemas for query params.

        resp = api_client.get(endpoint_path, params=params)

        assert resp.status_code == expected_status, f"Unexpected status for scenario '{sc.get('scenario', '')}': {resp.status_code} != {expected_status}"
        ctype = resp.headers.get("Content-Type", "")
        assert "application/json" in ctype.lower(), f"Expected JSON response, got Content-Type={ctype}"

        _assert_validated_response(swagger_validator, endpoint_path, http_method, "200", resp)


def test_list_pipelines_pagination_next_link(
    api_client,
    swagger_validator: SwaggerSchemaValidator,
    endpoint_path: str,
    http_method: str,
    merged_scenarios: List[Dict[str, Any]],
):
    """
    If next_page_token is present in the first 200 response, request the next page using that token.
    Validates both responses against their schemas.
    """
    for sc in merged_scenarios:
        expected_status = sc.get("expected_status")
        if expected_status != 200:
            # Only meaningful for success scenarios
            continue

        params = dict(sc.get("params") or {})
        resp1 = api_client.get(endpoint_path, params=params)
        assert resp1.status_code == 200, f"First page request failed for scenario '{sc.get('scenario', '')}'."
        _assert_validated_response(swagger_validator, endpoint_path, http_method, "200", resp1)

        body1 = _extract_json(resp1)
        token = body1.get("next_page_token")

        # If there is a next page token, follow it
        if token:
            next_params = dict(params)
            next_params["page-token"] = token
            resp2 = api_client.get(endpoint_path, params=next_params)
            assert resp2.status_code == 200, f"Second page request failed for scenario '{sc.get('scenario', '')}'."
            _assert_validated_response(swagger_validator, endpoint_path, http_method, "200", resp2)


def test_list_pipelines_default_error_schema_with_mutated_params(
    api_client,
    swagger_validator: SwaggerSchemaValidator,
    endpoint_path: str,
    http_method: str,
    merged_scenarios: List[Dict[str, Any]],
):
    """
    Attempts to provoke default error responses by mutating scenario-driven parameters
    without hardcoding values. If the server still returns 200, validates success schema.
    If non-200, validates against the default error schema defined in the spec.
    """
    for sc in merged_scenarios:
        base_params = dict(sc.get("params") or {})

        mutated_params = dict(base_params)

        # Mutate page-token if present by reversing it (derived from data)
        if "page-token" in mutated_params and isinstance(mutated_params["page-token"], str):
            mutated_params["page-token"] = mutated_params["page-token"][::-1]  # derived from provided data

        # Mutate mine if present by converting to an obviously wrong type (derived)
        if "mine" in mutated_params:
            # Using scenario text as value to avoid hardcoding arbitrary literals
            mutated_params["mine"] = str(sc.get("scenario", ""))

        # If neither parameter existed, introduce a mutation derived from scenario to attempt an error.
        if "page-token" not in base_params and "mine" not in base_params:
            # Introduce a page-token derived from scenario text
            scenario_text = str(sc.get("scenario", ""))
            if scenario_text:
                mutated_params["page-token"] = scenario_text[::-1]

        resp = api_client.get(endpoint_path, params=mutated_params)

        if resp.status_code == 200:
            # Still successful; validate as success.
            _assert_validated_response(swagger_validator, endpoint_path, http_method, "200", resp)
        else:
            # Non-200: validate against the default error schema.
            _assert_validated_response(swagger_validator, endpoint_path, http_method, "default", resp)


# ----------------------------
# Instructions (as comments)
# ----------------------------
# Setup and Execution:
# 1) Ensure the following files are present in the same directory:
#    - conftest.py           (provided)
#    - validator.py          (provided)
#    - api.json              (OpenAPI 3.x spec of the API)
#    - pipeline.json         (ENDPOINT_TEST_DATA; see example provided by the prompt)
#    - config.yml            (see provided template; uses env expansion)
#
# 2) Configure environment variables as needed for config.yml:
#    - API_HOST (optional; defaults to https://circleci.com/api/v2)
#    - Circle-Token and/or circle-token for authentication (if required)
#    - TEST_org-slug, etc., for default test_data overrides (optional)
#
# 3) Install dependencies:
#    - pip install -r requirements.txt
#      Requirements should include: pytest, requests, pyyaml, jsonschema, referencing
#
# 4) Run tests:
#    - All tests:         pytest -q
#    - Smoke tests only:  pytest -q -m smoke
#
# Notes:
# - Authentication is automatically applied from config.yml by APIClient in conftest.py.
# - Do not modify hardcoded values for success scenarios; test data is loaded from pipeline.json and config.yml.
# - This suite validates responses exclusively using SwaggerSchemaValidator methods.
