# ********RoostGPT********

# Test generated by RoostGPT for test api-testing-pytest-weatherapi using AI Type Open AI and AI Model gpt-5
# 
# Test file generated for /project/{project-slug}_delete for http method type DELETE 
# RoostTestHash=caa6efeb67
# 
# 

# ********RoostGPT********
"""
Pytest test suite for RESTful API endpoint: DELETE /project/{project-slug}

Summary (Step 1: Analysis)
- Endpoints:
  - DELETE /project/{project-slug}

- Security Schemas:
  - API Key via HTTP header: "Circle-Token" (value provided via fixture auth_api_key_header from config.yml/env)
  - API Key via Query Parameter: "circle-token" (value provided via fixture auth_api_key_query from config.yml/env)

- Parameters:
  - Path:
    - project-slug (string, required). Example: "gh/CircleCI-Public/api-preview-docs"
    - allowReserved: true

- Responses (per OpenAPI):
  - 200:
    - application/json -> schema: MessageResponse (object, required property: "message")
  - default:
    - application/json -> schema: object with "message" (string). Used for non-2xx responses.

- Request/Response Schemas and Data Models:
  - Request has no body. Only one required path parameter as described above.
  - Response schemas validated strictly via SwaggerSchemaValidator, using api.json:
    - Success: response validated against the "200" response schema for DELETE /project/{project-slug}
    - Error/other: response validated against the "default" response schema for DELETE /project/{project-slug}

- Required vs Optional:
  - Required: project-slug
  - Optional: None for request body (no body)

Notes:
- Table-driven tests read scenario data from JSON file located alongside this test: project_project-slug.json
- Dynamic values (e.g., project-slug, expected statusCode) are taken from the JSON file and/or config_test_data fixture, never hardcoded in test functions.
- Authentication tests (valid/invalid/missing) are defined but skipped here, as authentication is covered in test_authentication.py
- All response schema validations are done through SwaggerSchemaValidator using api.json.
- Due to the "default" response block in the OpenAPI spec, for non-200 responses we validate with status key "default" and assert that status code is not 2xx.

Instructions for running the tests:
- Ensure files present in same directory:
  - conftest.py (provided)
  - config.yml with appropriate environment expansions (provided)
  - validator.py with SwaggerSchemaValidator (provided)
  - api.json (OpenAPI spec for validation)
  - project_project-slug.json (ENDPOINT_TEST_DATA for this endpoint)
- Configure environment variables used by config.yml as needed (e.g., API_HOST, Circle-Token).
- Execute: pytest -q
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any, Dict, List, Optional
from urllib.parse import quote

import pytest

from validator import SwaggerSchemaValidator


# ---------------------------
# Module-level configuration
# ---------------------------

_HERE = Path(__file__).resolve().parent
_TEST_DATA_FILENAME = "project_project-slug.json"
_ENDPOINT_DATA_PATH = _HERE / _TEST_DATA_FILENAME

_SPEC_PATH = str((_HERE / "api.json").resolve())

def _load_json_file(path: Path) -> List[Dict[str, Any]]:
    """
    Load JSON test data with robust error handling.
    """
    if not path.exists():
        # Gracefully handle missing file: no cases -> tests skipped in execution when no data.
        return []
    try:
        with path.open("r", encoding="utf-8") as f:
            data = json.load(f)
        if not isinstance(data, list):
            raise pytest.UsageError(f"Expected a JSON array in {path}, got: {type(data).__name__}")
        return data
    except json.JSONDecodeError as e:
        raise pytest.UsageError(f"Invalid JSON in {path}: {e}") from e


def _param_ids(cases: List[Dict[str, Any]]) -> List[str]:
    """
    Generate readable param ids from cases.
    """
    ids: List[str] = []
    for i, c in enumerate(cases):
        scenario = c.get("scenario") or f"case-{i+1}"
        slug = c.get("project-slug") or "<from-config>"
        status = c.get("statusCode", "<unspecified>")
        ids.append(f"{scenario} | slug={slug} | expect={status}")
    return ids


_ENDPOINT_DATA = _load_json_file(_ENDPOINT_DATA_PATH)
_PARAM_CASES = _ENDPOINT_DATA
_PARAM_IDS = _param_ids(_ENDPOINT_DATA)

_VALIDATOR = SwaggerSchemaValidator(_SPEC_PATH)


# ---------------------------
# Helper factories/builders
# ---------------------------

def _resolve_project_slug(scenario_case: Dict[str, Any], default_data: Dict[str, Any]) -> Optional[str]:
    """
    Resolve the project-slug with priority: scenario case -> config_test_data.
    Returns None if missing or empty after stripping.
    """
    val = (scenario_case.get("project-slug") or default_data.get("project-slug") or "").strip()
    return val or None


def _expected_status_code_for_case(scenario_case: Dict[str, Any]) -> Optional[int]:
    """
    Retrieve the expected status code from the scenario if provided.
    """
    val = scenario_case.get("statusCode")
    return int(val) if isinstance(val, int) else None


def _build_endpoint(slug: str) -> str:
    """
    Build the request path using provided project slug.
    Slashes are allowed per spec; do not encode slashes for the primary test path.
    """
    return f"/project/{slug}"


def _build_endpoint_with_escaped_slug(slug: str) -> str:
    """
    Build the request path using URL-escaped slug. This condenses the entire slug into one segment.
    This tests the 'allowReserved' behavior with explicit escaping.
    """
    escaped = quote(slug, safe="")  # encode all reserved chars, including '/'
    return f"/project/{escaped}"


def _status_key_for_response_code(status_code: int) -> str:
    """
    Map HTTP status to OpenAPI response key for schema validation.
    Return "200" for 200, otherwise "default".
    """
    return "200" if status_code == 200 else "default"


def _validate_response_schema(endpoint_template: str, method: str, response) -> None:
    """
    Validate the response schema using SwaggerSchemaValidator.
    endpoint_template must match the OpenAPI path template exactly (e.g., '/project/{project-slug}').
    """
    status_key = _status_key_for_response_code(response.status_code)
    result = _VALIDATOR.validate_schema_by_response(endpoint_template, method, status_key, response)
    assert result.get("valid"), f"Schema validation failed: {result}"


def _build_auth_headers(token: str) -> Dict[str, str]:
    """
    Build auth headers using the provided API key token per spec.
    """
    return {"Circle-Token": token} if token else {}


def _build_auth_query_params(token: str) -> Dict[str, str]:
    """
    Build auth query parameters using the provided API key token per spec.
    """
    return {"circle-token": token} if token else {}


def _skip_if_no_test_cases() -> None:
    """
    Skip tests gracefully if test data file is missing or empty.
    """
    if not _PARAM_CASES:
        pytest.skip(f"No test cases found in '{_TEST_DATA_FILENAME}'")


# ---------------------------
# Tests
# ---------------------------

@pytest.mark.smoke
@pytest.mark.parametrize("scenario_case", _PARAM_CASES, ids=_PARAM_IDS)
def test_delete_project_smoke_success(api_client, auth_api_key_header, config_test_data, scenario_case):
    """
    Smoke test for DELETE /project/{project-slug}
    - Uses only required data.
    - Uses header-based API key for auth.
    - Validates response schema via SwaggerSchemaValidator.
    - Asserts status code when provided by ENDPOINT_TEST_DATA.
    """
    _skip_if_no_test_cases()

    slug = _resolve_project_slug(scenario_case, config_test_data)
    if not slug:
        pytest.skip("Missing required 'project-slug' in scenario_case and config_test_data")

    token = (auth_api_key_header or "").strip()
    if not token:
        pytest.skip("Missing API token (auth_api_key_header). Provide via config.yml/env.")

    endpoint = _build_endpoint(slug)
    headers = _build_auth_headers(token)

    response = api_client.delete(endpoint, headers=headers)

    expected_status = _expected_status_code_for_case(scenario_case)
    if expected_status is not None:
        assert response.status_code == expected_status, f"Expected {expected_status}, got {response.status_code}"

    # Validate response body schema against OpenAPI spec
    _validate_response_schema("/project/{project-slug}", "DELETE", response)

    # If 'default' response applies, ensure not 2xx per instructions about default cases
    if response.status_code != 200:
        assert not (200 <= response.status_code < 300), f"Expected non-2xx for default block, got {response.status_code}"


@pytest.mark.parametrize("scenario_case", _PARAM_CASES, ids=_PARAM_IDS)
def test_delete_project_error_default_with_invalid_slug(api_client, auth_api_key_header, config_test_data, scenario_case):
    """
    Negative test using a derived invalid slug to exercise the 'default' error response.
    - Slug is derived from valid slug (no hardcoded payloads).
    - Uses header-based API key for auth.
    - Validates response schema for 'default' block.
    """
    _skip_if_no_test_cases()

    slug = _resolve_project_slug(scenario_case, config_test_data)
    if not slug:
        pytest.skip("Missing required 'project-slug' in scenario_case and config_test_data")

    token = (auth_api_key_header or "").strip()
    if not token:
        pytest.skip("Missing API token (auth_api_key_header). Provide via config.yml/env.")

    # Derive an invalid slug without hardcoding a fixed value
    invalid_slug = f"{slug}-nonexistent-invalid"
    endpoint = _build_endpoint(invalid_slug)
    headers = _build_auth_headers(token)

    response = api_client.delete(endpoint, headers=headers)

    # For error path, assert that we didn't receive a 2xx as per 'default' response rule
    if response.status_code == 200:
        # Unexpected success; still validate as 200 schema
        _validate_response_schema("/project/{project-slug}", "DELETE", response)
        pytest.skip("Endpoint returned 200 for invalid slug; skipping error assertions.")
    else:
        _validate_response_schema("/project/{project-slug}", "DELETE", response)
        assert not (200 <= response.status_code < 300), f"Expected non-2xx for invalid slug, got {response.status_code}"


@pytest.mark.parametrize("scenario_case", _PARAM_CASES, ids=_PARAM_IDS)
def test_delete_project_with_url_escaped_slug(api_client, auth_api_key_header, config_test_data, scenario_case):
    """
    Test DELETE with URL-escaped slug (encodes slashes) to verify handling when allowReserved is true.
    - Uses header-based API key for auth.
    - Validates schema for 200 or default accordingly.
    """
    _skip_if_no_test_cases()

    slug = _resolve_project_slug(scenario_case, config_test_data)
    if not slug:
        pytest.skip("Missing required 'project-slug' in scenario_case and config_test_data")

    token = (auth_api_key_header or "").strip()
    if not token:
        pytest.skip("Missing API token (auth_api_key_header). Provide via config.yml/env.")

    endpoint = _build_endpoint_with_escaped_slug(slug)
    headers = _build_auth_headers(token)

    response = api_client.delete(endpoint, headers=headers)

    _validate_response_schema("/project/{project-slug}", "DELETE", response)

    # If default schema applied, ensure non-2xx per default rule
    if response.status_code != 200:
        assert not (200 <= response.status_code < 300), f"Expected non-2xx for default block, got {response.status_code}"


# ---------------------------------------
# Security schema tests (defined but skipped)
# ---------------------------------------

@pytest.mark.parametrize("scenario_case", _PARAM_CASES, ids=_PARAM_IDS)
def test_delete_project_auth_via_header_skipped(api_client, auth_api_key_header, config_test_data, scenario_case):
    """
    Placeholder test for header-based API key auth on DELETE /project/{project-slug}.
    Authentication tests are handled in test_authentication.py, so this is skipped here.
    """
    pytest.skip("Authentication behavior is tested in test_authentication.py")


@pytest.mark.parametrize("scenario_case", _PARAM_CASES, ids=_PARAM_IDS)
def test_delete_project_auth_via_query_param_skipped(api_client, auth_api_key_query, config_test_data, scenario_case):
    """
    Placeholder test for query-parameter-based API key auth on DELETE /project/{project-slug}.
    Authentication tests are handled in test_authentication.py, so this is skipped here.
    """
    pytest.skip("Authentication behavior is tested in test_authentication.py")
