# ********RoostGPT********

# Test generated by RoostGPT for test api-testing-pytest-weatherapi using AI Type Open AI and AI Model gpt-5
# 
# Test file generated for /me_get for http method type GET 
# RoostTestHash=e56f807845
# 
# 

# ********RoostGPT********
# test_me_endpoint.py
# =============================================================================
# Summary: Identified Endpoints, Methods, Security, and Responses
# - Endpoint(s):
#   - GET /me
# - Security:
#   - API key via HTTP header "Circle-Token" (provided through config/auth fixtures).
#   - Optional API key via query parameter "circle-token" (configured via auth fixtures).
#   - Authentication-specific tests are intentionally skipped here; they live in a dedicated test_authentication.py.
# - Responses:
#   - 200: application/json with schema "User" (required fields: avatar_url, id (uuid), login, name)
#   - default: application/json with schema { message: string } for error responses
#
# Notes:
# - This suite uses only fixtures from conftest.py for host/auth/api client/config data.
# - Request/response validation leverages SwaggerSchemaValidator from validator.py.
# - Table-driven tests read from me.json (ENDPOINT_TEST_DATA) and iterate over all entries.
# - Success scenario (smoke) asserts status codes from me.json and validates response against the OpenAPI schema.
# - Error scenario validation is conditional: if the API returns a non-200, the response is validated against the "default" error schema.
# - No request payloads, headers, or expected values are hardcoded for success paths; all dynamic expectations (e.g., status codes)
#   are sourced from ENDPOINT_TEST_DATA or config_test_data.
#
# Instructions to run:
# - Ensure these files exist in the same directory:
#   - conftest.py
#   - config.yml
#   - validator.py
#   - api.json (OpenAPI spec)
#   - me.json (ENDPOINT_TEST_DATA)
# - Export env vars if needed (e.g., API_HOST, Circle-Token, circle-token), or rely on defaults in config.yml.
# - Execute:
#     pytest -q -m smoke
#   or full suite:
#     pytest -q
# =============================================================================

from pathlib import Path
from typing import Any, Dict, List

import json
import pytest

from validator import SwaggerSchemaValidator


# ---------------------------
# Local fixtures and utilities
# ---------------------------

@pytest.fixture(scope="session")
def openapi_spec_path() -> str:
    """
    Provide the path to the OpenAPI specification file (api.json) co-located with this test file.
    """
    return str(Path(__file__).with_name("api.json"))


@pytest.fixture(scope="session")
def validator(openapi_spec_path: str) -> SwaggerSchemaValidator:
    """
    Initialize a shared SwaggerSchemaValidator to validate all responses against api.json.
    """
    return SwaggerSchemaValidator(openapi_spec_path)


@pytest.fixture(scope="session")
def endpoint_path() -> str:
    """
    Endpoint path under test.
    """
    return "/me"


@pytest.fixture(scope="session")
def http_method() -> str:
    """
    HTTP method under test.
    """
    return "GET"


@pytest.fixture(scope="session")
def endpoint_test_data() -> List[Dict[str, Any]]:
    """
    Load table-driven ENDPOINT_TEST_DATA from me.json located alongside this test file.
    Each object is used to drive a test iteration.
    """
    path = Path(__file__).with_name("me.json")
    if not path.exists():
        raise pytest.UsageError(f"ENDPOINT_TEST_DATA not found: {path}")
    with path.open("r", encoding="utf-8") as f:
        data = json.load(f)
        if not isinstance(data, list):
            raise pytest.UsageError("ENDPOINT_TEST_DATA must be a JSON array")
        return data


@pytest.fixture
def merged_test_data(config_test_data: Dict[str, Any], request) -> Dict[str, Any]:
    """
    Merge common test_data from config.yml with the scenario-specific record
    from ENDPOINT_TEST_DATA for the current parameterized test instance.

    Priority:
      - Scenario-specific record values override config_test_data where keys overlap.

    This fulfills the requirement to not hardcode any values and to override defaults
    with scenario-specific data.
    """
    record = getattr(request, "param", {}) or {}
    merged = dict(config_test_data or {})
    merged.update(record or {})
    return merged


# ---------------------------
# Helpers
# ---------------------------

def _ids_from_endpoint_data(dataset: List[Dict[str, Any]]) -> List[str]:
    """
    Generate readable IDs for parametrize based on record content.
    """
    ids: List[str] = []
    for idx, rec in enumerate(dataset):
        scenario = str(rec.get("scenario", f"rec-{idx}")).strip() or f"rec-{idx}"
        login = str(rec.get("login", "")).strip()
        status_code = str(rec.get("statusCode", "")).strip()
        label = f"{scenario}::{login or idx}::status-{status_code or 'unknown'}"
        ids.append(label)
    return ids


# ---------------------------
# Tests
# ---------------------------

@pytest.mark.smoke
@pytest.mark.parametrize(
    "merged_test_data",
    argvalues=lambda endpoint_test_data: endpoint_test_data,  # filled by indirect below
    ids=lambda endpoint_test_data: _ids_from_endpoint_data(endpoint_test_data),
    indirect=True,
)
def test_get_me_smoke_success(
    api_client,
    validator: SwaggerSchemaValidator,
    endpoint_path: str,
    http_method: str,
    merged_test_data: Dict[str, Any],
    endpoint_test_data,  # kept for ids to resolve the lambda callables above
):
    """
    Smoke: Validates the happy path for GET /me.
    - Uses only required inputs (none for GET /me; auth is handled by fixtures).
    - Expects status codes provided via ENDPOINT_TEST_DATA.
    - Validates response body using the OpenAPI schema for 200.
    """
    # Arrange
    expected_status_str = str(merged_test_data.get("statusCode", "200")).strip()
    try:
        expected_status = int(expected_status_str)
    except ValueError:
        pytest.skip(f"Invalid statusCode in test data: {expected_status_str!r}")

    # No request payloads; request validation step is not applicable (no request body schema).
    # Authentication is injected by the api_client via fixtures and is tested elsewhere.

    # Act
    resp = api_client.get(endpoint_path)

    # Assert
    assert resp.status_code == expected_status, (
        f"Unexpected status code for {http_method} {endpoint_path}. "
        f"Expected {expected_status}, got {resp.status_code}. "
        f"Body: {resp.text[:500]}"
    )

    # Validate response schema strictly against the defined OpenAPI spec for 200.
    res = validator.validate_schema_by_response(endpoint=endpoint_path, method=http_method, status_code="200", response=resp)
    assert res.get("valid") is True, f"Schema validation failed: {json.dumps(res, default=str)}"


@pytest.mark.parametrize(
    "merged_test_data",
    argvalues=lambda endpoint_test_data: endpoint_test_data,
    ids=lambda endpoint_test_data: _ids_from_endpoint_data(endpoint_test_data),
    indirect=True,
)
def test_get_me_error_default_schema_when_non_200(
    api_client,
    validator: SwaggerSchemaValidator,
    endpoint_path: str,
    http_method: str,
    merged_test_data: Dict[str, Any],
    endpoint_test_data,
):
    """
    Validates the default error schema if the API responds with a non-200 code.
    We do not actively induce error responses here (auth tests are separate). If the
    live response is 200, this test is skipped for that iteration.
    """
    # Act
    resp = api_client.get(endpoint_path)

    # If success, skip error-schema check to avoid false failures in healthy environments.
    if resp.status_code == 200:
        pytest.skip("Received 200; default error schema not applicable for this iteration.")

    # Validate using the 'default' response block as defined in the spec.
    res = validator.validate_schema_by_response(endpoint=endpoint_path, method=http_method, status_code="default", response=resp)
    assert res.get("valid") is True, f"Default error schema validation failed: {json.dumps(res, default=str)}"


@pytest.mark.parametrize(
    "merged_test_data",
    argvalues=lambda endpoint_test_data: endpoint_test_data,
    ids=lambda endpoint_test_data: _ids_from_endpoint_data(endpoint_test_data),
    indirect=True,
)
def test_get_me_is_json_and_matches_declared_schema(
    api_client,
    validator: SwaggerSchemaValidator,
    endpoint_path: str,
    http_method: str,
    merged_test_data: Dict[str, Any],
    endpoint_test_data,
):
    """
    Additional coverage:
    - Ensures the server returns JSON for success scenarios per spec.
    - Validates schema using the OpenAPI definition for 200.
    """
    resp = api_client.get(endpoint_path)

    if resp.status_code != 200:
        pytest.skip(f"Non-200 received ({resp.status_code}); this test covers only 200 JSON responses.")

    ctype = resp.headers.get("Content-Type", "")
    assert "json" in ctype.lower(), f"Expected JSON content-type, got: {ctype!r}"

    res = validator.validate_schema_by_response(endpoint=endpoint_path, method=http_method, status_code="200", response=resp)
    assert res.get("valid") is True, f"Schema validation failed for JSON 200: {json.dumps(res, default=str)}"
