# ********RoostGPT********

# Test generated by RoostGPT for test api-testing-pytest-weatherapi using AI Type Open AI and AI Model gpt-5
# 
# Test file generated for /pipeline/{pipeline-id}_get for http method type GET 
# RoostTestHash=8cd9f60556
# 
# 

# ********RoostGPT********
"""
Pytest test suite for the RESTful API endpoint defined in the provided OpenAPI specification.

Summary of API endpoints and security schemas
- Endpoints (paths + methods):
  - GET /pipeline/{pipeline-id}
- Security schema(s):
  - API Key via header "Circle-Token" (as exemplified in API spec and config)
  - Optional API Key via query param "circle-token" (available in config.yml; not explicitly in API spec)
- Responses defined in spec for GET /pipeline/{pipeline-id}:
  - 200: Pipeline (application/json)
  - default: Error response (application/json; schema: { "message": "string" })

Test strategy overview
- Table-driven tests using pipeline_pipeline-id.json (ENDPOINT_TEST_DATA), merged at runtime with config-provided test data (config_test_data fixture) for required data.
- Smoke success tests only include required data (path param: pipeline-id).
- Error/default tests derive invalid cases from ENDPOINT_TEST_DATA without hardcoding literal values.
- Response schema validation uses SwaggerSchemaValidator from validator.py:
  - validate_schema_by_response(path_template, method, status_code_or_default, response)
- Authentication tests (e.g., missing/invalid token) are intentionally skipped in this module per requirements; they are covered in a dedicated test_authentication.py.

How to run
- Ensure the following files exist alongside this test module:
  - conftest.py (provided)
  - config.yml (provided; environment-expanded)
  - validator.py (provided; contains SwaggerSchemaValidator)
  - api.json (OpenAPI spec for validation)
  - pipeline_pipeline-id.json (endpoint test data)
- Export environment variables for tokens and test data as needed:
  - Circle-Token (header-based API key)
  - Optional: circle-token (query-based API key)
  - TEST_pipeline-id and other test_data keys as needed
- Execute with: pytest -q

Notes
- Request validation prior to sending is constrained by the absence of explicit request schemas for the path parameter in the provided spec; response validation strictly uses validator APIs.
- Authentication scenarios are intentionally skipped in this module.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any, Dict, Iterable, List, Mapping, Optional

import pytest
from validator import SwaggerSchemaValidator


# -----------------------------
# Module-level configuration
# -----------------------------

HERE = Path(__file__).resolve().parent
SPEC_PATH = str(HERE / "api.json")
TEST_DATA_FILENAME = "pipeline_pipeline-id.json"

# API path template and method as defined by the spec
PATH_TEMPLATE = "/pipeline/{pipeline-id}"
HTTP_METHOD = "GET"


def _load_json_file(path: Path) -> List[Dict[str, Any]]:
    if not path.exists():
        raise pytest.UsageError(f"Required test data file not found: {path}")
    try:
        with path.open("r", encoding="utf-8") as f:
            data = json.load(f)
        if not isinstance(data, list):
            raise pytest.UsageError(f"Test data must be a JSON array at: {path}")
        return data
    except json.JSONDecodeError as e:
        raise pytest.UsageError(f"Invalid JSON in {path}: {e}") from e


def _param_ids(cases: Iterable[Mapping[str, Any]]) -> List[str]:
    ids: List[str] = []
    for c in cases:
        scenario = c.get("scenario") or ""
        pid = c.get("pipeline-id") or ""
        if scenario and pid:
            ids.append(f"{scenario} | {pid}")
        elif scenario:
            ids.append(scenario)
        elif pid:
            ids.append(pid)
        else:
            ids.append("case")
    return ids


# Load endpoint test data at import time for parametrization
_ENDPOINT_DATA_PATH = HERE / TEST_DATA_FILENAME
_ENDPOINT_DATA = _load_json_file(_ENDPOINT_DATA_PATH)
_PARAM_CASES = _ENDPOINT_DATA
_PARAM_IDS = _param_ids(_ENDPOINT_DATA)


# -----------------------------
# Fixtures
# -----------------------------

@pytest.fixture(scope="session")
def schema_validator() -> SwaggerSchemaValidator:
    """
    Session-scoped validator initialized with the API specification.
    """
    return SwaggerSchemaValidator(SPEC_PATH)


# -----------------------------
# Utilities
# -----------------------------

def _resolve_pipeline_id(scenario_case: Mapping[str, Any], config_test_data: Mapping[str, Any]) -> Optional[str]:
    """
    Resolve pipeline-id from scenario-specific data with fallback to default config test data.
    """
    pid = scenario_case.get("pipeline-id") or config_test_data.get("pipeline-id")
    pid = (pid or "").strip()
    return pid or None


def _build_endpoint_from_template(pipeline_id: str) -> str:
    """
    Build endpoint path by replacing template token in the path with provided pipeline_id.
    """
    return PATH_TEMPLATE.replace("{pipeline-id}", pipeline_id)


def _headers_for_success(auth_api_key_header: str) -> Dict[str, str]:
    """
    Construct authorization headers for success scenarios.
    """
    headers: Dict[str, str] = {}
    if auth_api_key_header:
        # API spec examples use header "Circle-Token"
        headers["Circle-Token"] = auth_api_key_header
    return headers


def _derive_invalid_pipeline_id(valid_id: str) -> str:
    """
    Derive an invalid pipeline id from the provided valid id without hardcoding a literal invalid value.
    Strategy: append '-x' to ensure non-UUID format.
    """
    suffix = "-x"
    if valid_id.endswith(suffix):
        return valid_id + "z"
    return f"{valid_id}{suffix}"


def _validate_response_schema(
    schema_validator: SwaggerSchemaValidator,
    response,
    status_code: int,
) -> None:
    """
    Validate response against the OpenAPI spec for the endpoint and method.
    Uses '200' on 2xx, otherwise uses 'default' as defined by the spec.
    """
    if 200 <= status_code < 300:
        code_key = "200"
    else:
        code_key = "default"
    result = schema_validator.validate_schema_by_response(PATH_TEMPLATE, HTTP_METHOD, code_key, response)
    assert result.get("valid") is True, f"Schema validation failed for {code_key}: {result}"


# -----------------------------
# Tests
# -----------------------------

@pytest.mark.smoke
@pytest.mark.parametrize("scenario_case", _PARAM_CASES, ids=_PARAM_IDS)
def test_get_pipeline_by_id_smoke_success(
    api_client,
    config_test_data,
    auth_api_key_header,
    schema_validator: SwaggerSchemaValidator,
    scenario_case: Mapping[str, Any],
):
    """
    Smoke test: GET /pipeline/{pipeline-id} success path.
    - Uses only required parameter: pipeline-id
    - Token is required for this endpoint; skipped if missing
    - Validates response schema for 200 per OpenAPI spec
    """
    # Resolve required path param
    pipeline_id = _resolve_pipeline_id(scenario_case, config_test_data)
    if not pipeline_id:
        pytest.skip("Missing required pipeline-id in both scenario data and config_test_data")

    # Build authorization headers; skip if token is not provided (auth tests are in separate module)
    headers = _headers_for_success(auth_api_key_header)
    if not headers.get("Circle-Token"):
        pytest.skip("Missing Circle-Token for authenticated request; provide via config/env")

    endpoint = _build_endpoint_from_template(pipeline_id)

    # Send request (no request body/params for this endpoint)
    response = api_client.get(endpoint, headers=headers)

    # Assert status code only if provided in test data (to avoid hardcoding)
    expected_status = scenario_case.get("statusCode")
    if expected_status is not None:
        assert response.status_code == int(expected_status), f"Unexpected status code for {endpoint}"

    # Validate response schema according to the status code block
    _validate_response_schema(schema_validator, response, response.status_code)


@pytest.mark.parametrize("scenario_case", _PARAM_CASES, ids=_PARAM_IDS)
def test_get_pipeline_by_id_default_error_with_invalid_id(
    api_client,
    config_test_data,
    auth_api_key_header,
    schema_validator: SwaggerSchemaValidator,
    scenario_case: Mapping[str, Any],
):
    """
    Negative/default test: GET /pipeline/{pipeline-id} with invalid path param derived from scenario data.
    - Ensures non-2xx response to hit 'default' response schema
    - Validates against 'default' block in the spec
    """
    pipeline_id = _resolve_pipeline_id(scenario_case, config_test_data)
    if not pipeline_id:
        pytest.skip("Missing required pipeline-id in both scenario data and config_test_data")

    invalid_pipeline_id = _derive_invalid_pipeline_id(pipeline_id)

    headers = _headers_for_success(auth_api_key_header)
    if not headers.get("Circle-Token"):
        pytest.skip("Missing Circle-Token for authenticated request; provide via config/env")

    endpoint = _build_endpoint_from_template(invalid_pipeline_id)

    response = api_client.get(endpoint, headers=headers)

    # For default error path, assert not 2xx (as per instruction for 'default')
    assert not (200 <= response.status_code < 300), "Expected non-2xx status for invalid pipeline-id"

    # Validate response with 'default' schema block
    _validate_response_schema(schema_validator, response, response.status_code)


@pytest.mark.parametrize("scenario_case", _PARAM_CASES, ids=_PARAM_IDS)
def test_get_pipeline_by_id_with_query_api_key_skipped(
    scenario_case: Mapping[str, Any],
    auth_api_key_query: str,
):
    """
    Security schema variation (query-token) - intentionally skipped.
    Authentication tests are covered in a dedicated test_authentication.py.
    """
    pytest.skip("Authentication variations are tested in test_authentication.py")


@pytest.mark.parametrize("scenario_case", _PARAM_CASES, ids=_PARAM_IDS)
def test_get_pipeline_by_id_missing_auth_skipped(
    scenario_case: Mapping[str, Any],
):
    """
    Missing authentication scenario - intentionally skipped.
    """
    pytest.skip("Authentication (missing/invalid) is tested in test_authentication.py")
