# ********RoostGPT********

# Test generated by RoostGPT for test api-testing-pytest-weatherapi using AI Type Open AI and AI Model gpt-5
# 
# Test file generated for /insights/{project-slug}/workflows/{workflow-name}/summary_get for http method type GET 
# RoostTestHash=b2014120ff
# 
# 

# ********RoostGPT********
"""
Pytest test suite for CircleCI Insights API: GET /insights/{project-slug}/workflows/{workflow-name}/summary

Summary:
- Endpoints:
  - GET /insights/{project-slug}/workflows/{workflow-name}/summary
- Security schemas supported by configuration:
  - API Key via header: Circle-Token
  - API Key via query: circle-token
- Responses:
  - 200: Workflow summary payload (metrics, trends, workflow_names)
  - default: Error response with message field

Notes:
- Authentication variations are tested in a dedicated test_authentication.py; these tests will skip if auth is not configured.
- This suite performs response schema validation strictly via SwaggerSchemaValidator against api.json.
- Test data is table-driven from insights_project-slug_workflows_workflow-name_summ.json and merged with config test_data.

How to run:
- Ensure api.json and the JSON test data file (insights_project-slug_workflows_workflow-name_summ.json) are present in the same directory as this test module.
- Provide config.yml alongside conftest.py as specified. Configure environment variables for auth and test_data as needed.
- Run: pytest -q
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any, Dict, Iterable, List, Tuple

import pytest

from validator import SwaggerSchemaValidator


# -----------------------------
# Module-level configuration
# -----------------------------
_API_PATH_TEMPLATE = "/insights/{project-slug}/workflows/{workflow-name}/summary"
_METHOD = "GET"

_HERE = Path(__file__).resolve().parent
_TEST_DATA_FILENAME = "insights_project-slug_workflows_workflow-name_summ.json"
_ENDPOINT_DATA_PATH = _HERE / _TEST_DATA_FILENAME
_API_SPEC_PATH = _HERE / "api.json"


def _load_json_file(path: Path) -> List[Dict[str, Any]]:
    try:
        with path.open("r", encoding="utf-8") as f:
            data = json.load(f)
        if not isinstance(data, list):
            return []
        return data
    except FileNotFoundError:
        # No test data file present; return empty to avoid parametrization errors
        return []
    except json.JSONDecodeError:
        # Malformed test data; return empty set
        return []


def _param_ids(cases: Iterable[Dict[str, Any]]) -> List[str]:
    ids: List[str] = []
    for i, c in enumerate(cases):
        scenario = c.get("scenario") or "case"
        p = c.get("project-slug") or "proj"
        w = c.get("workflow-name") or "wf"
        ids.append(f"{i}-{scenario}-{p}-{w}")
    return ids


def _merge_endpoint_case_with_config(
    base: Dict[str, Any], override: Dict[str, Any]
) -> Dict[str, Any]:
    """
    Merge config_test_data (base) with scenario-specific override from test data.
    For required path params, prefer values from base (fixture) if present; else fall back to override.
    Optional params are taken from override when provided.
    """
    merged = dict(base or {})
    # Always overlay everything from override
    merged.update(override or {})
    # For required path params in success tests, prefer fixture values if non-empty
    for key in ("project-slug", "workflow-name"):
        if base.get(key):
            merged[key] = base.get(key)
    return merged


def _encode_bool_param(value: Any) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return "true" if value else "false"
    if isinstance(value, str):
        return "true" if value.strip().lower() in ("true", "1", "t", "yes", "y") else "false"
    return "false"


def _build_endpoint(project_slug: str, workflow_name: str) -> str:
    # project-slug allows reserved "/" characters (allowReserved: true), so we do not escape slashes
    return f"/insights/{project_slug}/workflows/{workflow_name}/summary"


_ENDPOINT_DATA: List[Dict[str, Any]] = _load_json_file(_ENDPOINT_DATA_PATH)
_PARAM_CASES: List[Dict[str, Any]] = _ENDPOINT_DATA
_PARAM_IDS: List[str] = _param_ids(_ENDPOINT_DATA)

# Validator instance for response validation
_VALIDATOR = SwaggerSchemaValidator(str(_API_SPEC_PATH))


# -----------------------------
# Fixtures
# -----------------------------
@pytest.fixture(scope="function")
def auth_headers_params(auth_api_key_header: str, auth_api_key_query: str) -> Tuple[Dict[str, str], Dict[str, Any]]:
    """
    Build authentication headers/params from configured fixtures.
    - Prefer header API key if available; else fall back to query API key.
    """
    headers: Dict[str, str] = {}
    params: Dict[str, Any] = {}

    # Prefer header if provided
    if auth_api_key_header:
        headers["Circle-Token"] = auth_api_key_header
    elif auth_api_key_query:
        params["circle-token"] = auth_api_key_query

    return headers, params


# -----------------------------
# Tests
# -----------------------------
@pytest.mark.parametrize("scenario_case", _PARAM_CASES, ids=_PARAM_IDS)
@pytest.mark.smoke
def test_get_workflow_summary_smoke_success(
    api_client,
    api_host: str,
    config_test_data: Dict[str, Any],
    auth_headers_params: Tuple[Dict[str, str], Dict[str, Any]],
    scenario_case: Dict[str, Any],
):
    """
    Smoke: Success response with only required path params.
    Validates:
      - HTTP 200 as per scenario test data
      - Response schema matches OpenAPI spec for 200
    """
    if not api_host:
        pytest.skip("API host is not configured in config.yml")

    headers, auth_params = auth_headers_params
    if not headers and not auth_params:
        pytest.skip("No API authentication configured; skipping smoke test")

    # Merge config test data with scenario overrides (prefer fixture for required params)
    merged = _merge_endpoint_case_with_config(config_test_data, scenario_case)

    project_slug = merged.get("project-slug") or ""
    workflow_name = merged.get("workflow-name") or ""

    if not project_slug or not workflow_name:
        pytest.skip("Required path params are not available from config or test data")

    endpoint = _build_endpoint(project_slug, workflow_name)

    # For smoke, do not send optional query parameters; only auth params.
    params = dict(auth_params)

    response = api_client.get(endpoint, headers=headers, params=params)
    expected_status = int(scenario_case.get("statusCode", 200))
    assert response.status_code == expected_status, f"Expected {expected_status}, got {response.status_code}"

    # Validate response schema for 200 using the path template
    result = _VALIDATOR.validate_schema_by_response(_API_PATH_TEMPLATE, _METHOD, "200", response)
    assert result.get("valid"), f"Schema validation failed: {result}"


@pytest.mark.parametrize("scenario_case", _PARAM_CASES, ids=_PARAM_IDS)
def test_get_workflow_summary_optional_query_variants(
    api_client,
    api_host: str,
    config_test_data: Dict[str, Any],
    auth_headers_params: Tuple[Dict[str, str], Dict[str, Any]],
    scenario_case: Dict[str, Any],
):
    """
    Success variants: Exercise optional query parameters when provided in scenario data.
    Validates:
      - HTTP status per scenario (default 200)
      - Response schema matches OpenAPI spec for 200
    """
    if not api_host:
        pytest.skip("API host is not configured in config.yml")

    headers, auth_params = auth_headers_params
    if not headers and not auth_params:
        pytest.skip("No API authentication configured; skipping optional variants test")

    # Prefer fixture values for required path params where available
    merged = dict(config_test_data or {})
    merged.update(scenario_case or {})

    project_slug = (config_test_data.get("project-slug") or scenario_case.get("project-slug") or "").strip()
    workflow_name = (config_test_data.get("workflow-name") or scenario_case.get("workflow-name") or "").strip()

    if not project_slug or not workflow_name:
        pytest.skip("Required path params are not available from config or test data")

    endpoint = _build_endpoint(project_slug, workflow_name)

    params = dict(auth_params)

    # Optional query params when present in scenario data or config
    if "all-branches" in scenario_case:
        params["all-branches"] = _encode_bool_param(scenario_case.get("all-branches"))
    elif "all-branches" in config_test_data and config_test_data.get("all-branches") not in (None, ""):
        params["all-branches"] = _encode_bool_param(config_test_data.get("all-branches"))

    if "branch" in scenario_case and scenario_case.get("branch"):
        # Respect the mutual exclusion: if 'all-branches' also present, keep only one (favor scenario's explicit setting)
        if "all-branches" in params:
            params.pop("all-branches", None)
        params["branch"] = scenario_case.get("branch")
    elif "branch" in config_test_data and config_test_data.get("branch"):
        if "all-branches" in params:
            params.pop("all-branches", None)
        params["branch"] = config_test_data.get("branch")

    response = api_client.get(endpoint, headers=headers, params=params)
    expected_status = int(scenario_case.get("statusCode", 200))
    assert response.status_code == expected_status, f"Expected {expected_status}, got {response.status_code}"

    result = _VALIDATOR.validate_schema_by_response(_API_PATH_TEMPLATE, _METHOD, "200", response)
    assert result.get("valid"), f"Schema validation failed: {result}"


@pytest.mark.parametrize("scenario_case", _PARAM_CASES, ids=_PARAM_IDS)
def test_get_workflow_summary_error_default_conflicting_params(
    api_client,
    api_host: str,
    config_test_data: Dict[str, Any],
    auth_headers_params: Tuple[Dict[str, str], Dict[str, Any]],
    scenario_case: Dict[str, Any],
):
    """
    Error/default response: Send conflicting optional parameters ('all-branches' and 'branch') when both are available.
    Validates:
      - Non-2xx status code
      - Schema conforms to default error response
    """
    if not api_host:
        pytest.skip("API host is not configured in config.yml")

    headers, auth_params = auth_headers_params
    if not headers and not auth_params:
        pytest.skip("No API authentication configured; skipping default error test")

    # Required path params
    project_slug = (config_test_data.get("project-slug") or scenario_case.get("project-slug") or "").strip()
    workflow_name = (config_test_data.get("workflow-name") or scenario_case.get("workflow-name") or "").strip()

    if not project_slug or not workflow_name:
        pytest.skip("Required path params are not available from config or test data")

    # Need both 'all-branches' and 'branch' to attempt a conflicting request
    ab_src = scenario_case if "all-branches" in scenario_case else config_test_data
    br_src = scenario_case if "branch" in scenario_case else config_test_data

    if ("all-branches" not in ab_src) or (not br_src.get("branch")):
        pytest.skip("Both 'all-branches' and 'branch' not available; skipping conflict test")

    endpoint = _build_endpoint(project_slug, workflow_name)

    params = dict(auth_params)
    params["all-branches"] = _encode_bool_param(ab_src.get("all-branches"))
    params["branch"] = br_src.get("branch")

    response = api_client.get(endpoint, headers=headers, params=params)

    # For default case, assert non-2xx without converting 'default' to an int
    assert not (200 <= response.status_code < 300), f"Expected non-2xx for conflicting params, got {response.status_code}"

    # Validate using 'default' response schema from spec
    result = _VALIDATOR.validate_schema_by_response(_API_PATH_TEMPLATE, _METHOD, "default", response)
    assert result.get("valid"), f"Default schema validation failed: {result}"
