# ********RoostGPT********

# Test generated by RoostGPT for test api-testing-pytest-weatherapi using AI Type Open AI and AI Model gpt-5
# 
# Test file generated for /pipeline/{pipeline-id}/workflow_get for http method type GET 
# RoostTestHash=840fe668da
# 
# 

# ********RoostGPT********
"""
Summary of API endpoints, security, and responses (from provided OpenAPI spec)

Endpoints:
- GET /pipeline/{pipeline-id}/workflow
  - Description: Returns a paginated list of workflows by pipeline ID.
  - Required path params:
      - pipeline-id (string, uuid) [REQUIRED]
  - Optional query params:
      - page-token (string, allowEmptyValue=true) [OPTIONAL]
  - Success Responses:
      - 200: application/json -> WorkflowListResponse schema
        - items: array of Workflow (id, name, status, created_at, stopped_at, pipeline_id, pipeline_number, project_slug, started_by, ...)
        - next_page_token: string|null
  - Error Responses:
      - default: application/json -> {"message": "string"}

Security (as inferred from config and x-code-samples):
- API Key via:
  - Header: Circle-Token
  - Query: circle-token
- Note: Authentication tests are explicitly skipped in this suite per instructions. Auth handling is in a separate test_authentication.py.

Test data & configuration:
- Base configuration and credentials are provided via config.yml and loaded by conftest.py fixtures.
- Endpoint test data is provided by JSON file: pipeline_pipeline-id_workflow.json (located alongside this test file).
- Tests use config_test_data fixture for default values and override with scenario-specific JSON test data.
- All request/response schema validations are performed using SwaggerSchemaValidator from validator.py with api.json as the spec.

How to run:
- Ensure files present in the same directory:
  - conftest.py (provided)
  - config.yml (provided; configure API_HOST, Circle-Token, etc.)
  - api.json (OpenAPI spec used by validator)
  - pipeline_pipeline-id_workflow.json (endpoint scenario data)
- Install dependencies:
  - pip install -r requirements.txt
    (requirements should include: pytest, requests, pyyaml, jsonschema, referencing, urllib3)
- Execute tests:
  - pytest -q
  - For smoke tests only: pytest -m smoke -q
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional

import pytest
from validator import SwaggerSchemaValidator


# -------------------------
# Fixtures and test helpers
# -------------------------

@pytest.fixture(scope="session")
def openapi_spec_path() -> str:
    """
    Provides the path to the OpenAPI spec used by SwaggerSchemaValidator.
    """
    return "api.json"


@pytest.fixture(scope="session")
def validator(openapi_spec_path: str) -> SwaggerSchemaValidator:
    """
    Shared validator that validates responses against the OpenAPI spec.
    """
    return SwaggerSchemaValidator(openapi_spec_path)


@pytest.fixture(scope="session")
def endpoint_path_template() -> str:
    """
    Provides the OpenAPI path template as written in the spec.
    """
    return "/pipeline/{pipeline-id}/workflow"


@pytest.fixture(scope="session")
def endpoint_test_data() -> List[Dict[str, Any]]:
    """
    Load table-driven endpoint test data from pipeline_pipeline-id_workflow.json in the same folder.
    """
    data_path = Path(__file__).with_name("pipeline_pipeline-id_workflow.json")
    if not data_path.exists():
        raise pytest.UsageError(f"Missing required endpoint test data file: {data_path}")
    with data_path.open("r", encoding="utf-8") as f:
        return json.load(f) or []


def _build_request_inputs(
    row: Dict[str, Any],
    config_test_data: Dict[str, Any],
) -> Dict[str, Any]:
    """
    Build request path and query params from row data and defaults.
    - Required path param pipeline-id is taken from row, falling back to config_test_data['pipeline-id'].
    - Optional query param page-token is included only if provided in row.
    """
    pipeline_id = (row.get("pipeline-id") or config_test_data.get("pipeline-id") or "").strip()
    page_token = row.get("page-token", None)

    return {
        "pipeline_id": pipeline_id,
        "query_params": ({ "page-token": page_token } if page_token is not None else {}),
    }


def _row_id(row: Dict[str, Any], idx: int) -> str:
    """
    Produce a stable id for pytest.param ids.
    """
    scenario = (row.get("scenario") or "").strip() or f"scenario-{idx}"
    pid = (row.get("pipeline-id") or "").strip() or "no-pipeline-id"
    st = row.get("statusCode")
    return f"{scenario}::pipeline-id={pid}::expect={st}"


def _assert_schema_valid(
    validator: SwaggerSchemaValidator,
    endpoint_path_template: str,
    method: str,
    status_code_key: str,
    response,
) -> None:
    """
    Validate response JSON against the OpenAPI schema for endpoint/method/status.
    Uses only the validator methods per instruction.
    """
    result = validator.validate_schema_by_response(
        endpoint=endpoint_path_template,
        method=method,
        status_code=status_code_key,
        response=response,
    )
    assert result.get("valid"), f"Schema validation failed: {result}"


# -------------------------
# Contract and smoke checks
# -------------------------

def test_openapi_contract_has_endpoint(validator: SwaggerSchemaValidator, endpoint_path_template: str):
    """
    Ensure the path and GET operation exist in the OpenAPI document.
    """
    paths = validator.spec.get("paths") or {}
    assert endpoint_path_template in paths, f"Missing path in spec: {endpoint_path_template}"
    op = paths.get(endpoint_path_template, {}).get("get")
    assert isinstance(op, dict), f"Missing GET operation for: {endpoint_path_template}"
    # Basic presence of response codes per spec: 200 and default
    responses = op.get("responses") or {}
    assert "200" in responses, "Spec must define 200 response."
    assert "default" in responses, "Spec must define default error response."


@pytest.mark.smoke
@pytest.mark.parametrize(
    "row",
    argvalues=lambda endpoint_test_data: endpoint_test_data,  # will be resolved by pytest on collection
    ids=lambda row: (row.get("scenario") or "").strip() or "smoke-scenario",
    indirect=["row"],
)
def test_list_workflows_smoke_success(
    row: Dict[str, Any],
    api_client,  # from conftest.py
    config_test_data: Dict[str, Any],
    endpoint_path_template: str,
    validator: SwaggerSchemaValidator,
):
    """
    Smoke test: only required parameters (pipeline-id).
    Executes for all dataset rows but runs only for success scenarios (statusCode == 200).
    """
    expected_status = row.get("statusCode")
    if expected_status != 200:
        pytest.skip("Smoke test runs only for success scenarios (200).")

    inputs = _build_request_inputs(row, config_test_data)
    pipeline_id = inputs["pipeline_id"]
    if not pipeline_id:
        pytest.skip("Required parameter 'pipeline-id' not available from data or config_test_data.")

    # Required-only request (no page-token even if present in dataset)
    endpoint = f"/pipeline/{pipeline_id}/workflow"

    # Send request
    resp = api_client.get(endpoint)

    # Assert status code strictly
    assert resp.status_code == expected_status, f"Unexpected status code for smoke test: {resp.status_code}"

    # Validate response schema using validator against 200 response
    _assert_schema_valid(validator, endpoint_path_template, "get", "200", resp)


# -------------------------
# Table-driven endpoint tests
# -------------------------

@pytest.fixture
def row(request, endpoint_test_data: List[Dict[str, Any]]) -> Dict[str, Any]:
    """
    Indirect param resolver that yields each data row for parametric tests.
    """
    # pytest passes the actual row value here (caller's argvalues returns the list),
    # so just return it unmodified.
    return request.param


@pytest.mark.parametrize(
    "row",
    argvalues=lambda endpoint_test_data: [
        pytest.param(r, id=_row_id(r, i)) for i, r in enumerate(endpoint_test_data)
    ],
    indirect=True,
)
def test_list_workflows_status_and_schema(
    row: Dict[str, Any],
    api_client,  # from conftest.py
    config_test_data: Dict[str, Any],
    endpoint_path_template: str,
    validator: SwaggerSchemaValidator,
):
    """
    Validates status codes and response schemas for the list workflows endpoint.
    Uses table-driven data; sends optional page-token only if present in dataset row.
    """
    expected_status = row.get("statusCode")
    assert expected_status is not None, "Each dataset row must define 'statusCode'."

    inputs = _build_request_inputs(row, config_test_data)
    pipeline_id = inputs["pipeline_id"]
    if not pipeline_id:
        pytest.skip("Required parameter 'pipeline-id' not available from data or config_test_data.")

    query_params = inputs["query_params"]
    endpoint = f"/pipeline/{pipeline_id}/workflow"

    # Send request with required + optional params (optional included only if present in dataset)
    resp = api_client.get(endpoint, params=query_params)

    # Assert expected status code
    assert resp.status_code == expected_status, f"Expected {expected_status}, got {resp.status_code}"

    # Validate response schema:
    # - For 200: validate against '200'
    # - For any other: validate against 'default' as per spec structure
    status_key = "200" if resp.status_code == 200 else "default"
    _assert_schema_valid(validator, endpoint_path_template, "get", status_key, resp)

    # Additional lightweight sanity checks (not schema validation):
    # If 200, ensure 'items' and 'next_page_token' keys exist.
    if resp.status_code == 200:
        try:
            body = resp.json()
        except Exception as e:
            pytest.fail(f"Response not JSON-decodable: {e}")
        assert "items" in body and isinstance(body["items"], list), "Body must contain 'items' array."
        assert "next_page_token" in body, "Body must contain 'next_page_token' field."


@pytest.mark.parametrize(
    "row",
    argvalues=lambda endpoint_test_data: [
        pytest.param(r, id=_row_id(r, i)) for i, r in enumerate(endpoint_test_data)
    ],
    indirect=True,
)
def test_list_workflows_pagination_follow_next(
    row: Dict[str, Any],
    api_client,  # from conftest.py
    config_test_data: Dict[str, Any],
    endpoint_path_template: str,
    validator: SwaggerSchemaValidator,
):
    """
    If next_page_token is present in a 200 response, follow it with a subsequent request.
    Validates both responses against the OpenAPI schema.
    """
    expected_status = row.get("statusCode")
    if expected_status != 200:
        pytest.skip("Pagination follow-up applies only to successful 200 scenarios.")

    inputs = _build_request_inputs(row, config_test_data)
    pipeline_id = inputs["pipeline_id"]
    if not pipeline_id:
        pytest.skip("Required parameter 'pipeline-id' not available from data or config_test_data.")

    initial_params = inputs["query_params"]
    endpoint = f"/pipeline/{pipeline_id}/workflow"

    # First request
    resp1 = api_client.get(endpoint, params=initial_params or None)
    assert resp1.status_code == 200, f"Expected 200 for initial request, got {resp1.status_code}"
    _assert_schema_valid(validator, endpoint_path_template, "get", "200", resp1)

    # Parse next token
    try:
        body1 = resp1.json()
    except Exception as e:
        pytest.fail(f"Initial response not JSON-decodable: {e}")

    next_token = body1.get("next_page_token")
    if not next_token:
        pytest.skip("No next_page_token available to follow pagination.")

    # Second request using next_page_token from the response
    resp2 = api_client.get(endpoint, params={"page-token": next_token})
    # Per spec, success is 200; default covers errors. Validate accordingly.
    if resp2.status_code == 200:
        _assert_schema_valid(validator, endpoint_path_template, "get", "200", resp2)
    else:
        _assert_schema_valid(validator, endpoint_path_template, "get", "default", resp2)
