# ********RoostGPT********

# Test generated by RoostGPT for test Exi-PW-Karate-VertexAi using AI Type Vertex AI and AI Model claude-3-7-sonnet
# 
# Feature file generated for /laureate/{laureateID}_get for http method type GET 
# RoostTestHash=56bfcadf64
# 
# 

# ********RoostGPT********
Feature: Laureate API Tests

  Background:
    * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:4010')
    * url urlBase

  Scenario Outline: Get laureate by ID
    Given path '/2.1/laureate/<laureateID>'
    When method get
    Then status 200
    And match response == '#object'

    Examples:
      | read('laureate_laureateID_get.csv') |

  Scenario Outline: Get laureate with invalid ID format
    Given path '/2.1/laureate/<laureateID>'
    When method get
    Then status 400
    And match response.code == '#string'
    And match response.message == '#string'

    Examples:
      | laureateID |
      | abc        |
      |         -1 |
      |          0 |

  Scenario: Get laureate with non-existent ID
    Given path '/2.1/laureate/99999'
    When method get
    Then status 404
    And match response.code == '#string'
    And match response.message == '#string'

  Scenario: Get laureate with unprocessable entity
    Given path '/2.1/laureate/422'
    When method get
    Then status 422
    And match response.code == '#string'
    And match response.message == '#string'
