# ********RoostGPT********

# Test generated by RoostGPT for test api-spec using AI Type  and AI Model 
# 
# Feature file generated for /laureates_get for http method type GET 
# RoostTestHash=bb9ad621b1
# 
# 

# ********RoostGPT********
Feature: Test Nobel Prize Laureates API

  Background:
    * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:4010')
    * url urlBase
    * configure headers = { Authorization: '#(karate.properties["AUTH_TOKEN"])' }

  Scenario Outline: Validate GET /2.1/laureates with query parameters
    Given path '/2.1/laureates'
    And param offset = <offset>
    And param limit = <limit>
    And param sort = '<sort>'
    And param ID = <ID>
    And param name = '<name>'
    And param gender = '<gender>'
    And param motivation = '<motivation>'
    And param affiliation = '<affiliation>'
    And param residence = '<residence>'
    And param birthDate = <birthDate>
    And param birthDateTo = '<birthDateTo>'
    And param deathDate = '<deathDate>'
    And param deathDateTo = <deathDateTo>
    And param foundedDate = '<foundedDate>'
    And param birthCity = '<birthCity>'
    And param birthCountry = '<birthCountry>'
    And param birthContinent = '<birthContinent>'
    And param deathCity = '<deathCity>'
    And param deathCountry = '<deathCountry>'
    And param deathContinent = '<deathContinent>'
    And param foundedCity = '<foundedCity>'
    And param foundedCountry = '<foundedCountry>'
    And param foundedContinent = '<foundedContinent>'
    And param HeadquartersCity = '<HeadquartersCity>'
    And param HeadquartersCountry = '<HeadquartersCountry>'
    And param HeadquartersContinent = '<HeadquartersContinent>'
    And param nobelPrizeYear = <nobelPrizeYear>
    And param yearTo = <yearTo>
    And param nobelPrizeCategory = '<nobelPrizeCategory>'
    And param format = '<format>'
    And param csvLang = '<csvLang>'
    When method get
    Then status 200
    And match response.laureates == '#[]'
    And match response.meta == '#object'
    And match response.links == '#array'

    Examples:
      | read('laureates_get.csv') |
