# ********RoostGPT********

# Test generated by RoostGPT for test api-spec using AI Type Open AI and AI Model gpt-4o
# 
# Feature file generated for /nobelPrize/{category}/{year}_get for http method type GET 
# RoostTestHash=adfce3f1d2
# 
# 

# ********RoostGPT********
Feature: Nobel Prize API Tests

  Background:
    * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:4010')
    * url urlBase
    * configure headers = { Authorization: '#(karate.properties["AUTH_TOKEN"])' }

  Scenario Outline: Test GET Nobel Prize by Category and Year
    Given path '2.1/nobelPrize', '<category>', '<year>'
    When method GET
    Then status 200
    And match response == '#object'
    And match response.nobelPrize == '#object'
    And match response.nobelPrize.awardYear == '#number'
    And match response.nobelPrize.category == '#object'
    And match response.nobelPrize.category.en == '#string'
    And match response.nobelPrize.categoryFullName == '#object'
    And match response.nobelPrize.dateAwarded == '#string'
    And match response.nobelPrize.prizeAmount == '#number'
    And match response.nobelPrize.prizeAmountAdjusted == '#number'
    And match response.nobelPrize.topMotivation == '#object'
    And match response.nobelPrize.laureates == '#array'

    Examples:
      | read('nobelPrize_category_year_get.csv') |

  Scenario Outline: Test GET Nobel Prize with Invalid Year
    Given path '2.1/nobelPrize', '<category>', '<year>'
    When method GET
    Then status 400
    And match response == '#object'
    And match response.code == '#string'
    And match response.message == '#string'

    Examples:
      | category | year |
      | che      | 1899 |
      | eco      | 1800 |

  Scenario Outline: Test GET Nobel Prize with Non-existent Category
    Given path '2.1/nobelPrize', '<category>', '<year>'
    When method GET
    Then status 404
    And match response == '#object'
    And match response.code == '#string'
    And match response.message == '#string'

    Examples:
      | category | year |
      | xyz      | 2020 |
      | abc      | 2019 |

  Scenario Outline: Test GET Nobel Prize with Unprocessable Entity
    Given path '2.1/nobelPrize', '<category>', '<year>'
    When method GET
    Then status 422
    And match response == '#object'
    And match response.code == '#string'
    And match response.message == '#string'

    Examples:
      | category | year |
      | che      | 2021 |
      | eco      | 2022 |
