# ********RoostGPT********

# Test generated by RoostGPT for test pw-it-Karate-1761120770140 using AI Type AWS Bedrock Runtime AI and AI Model us.anthropic.claude-3-7-sonnet-20250219-v1:0
# 
# ROOST_METHOD_HASH=1225a4a07f
# ROOST_METHOD_SIG_HASH=3a429a7e0a
# 
#  ########## Scenario ########## 
# 
# {
#   feature: 'Feature: Credential Wallet API\r\n' +
#     '  As a user of the Credential Wallet API\r\n' +
#     '  I want to be able to perform CRUD operations on accounts\r\n' +
#     '  So that I can manage my account effectively',
#   background: 'Background:\r\n    Given the base URL is "http://localhost:8080"',
#   rule: null,
#   scenario: {
#     title: 'Scenario: Create my account',
#     steps: 'When the client sends a POST request "/accounts" with the accounts_body payload\r\n' +
#       'Then create an account with the specified informatio\r\n' +
#       'And verify the account created using GET request for "/me"',
#     examples: ''
#   }
# }
# 

# ********RoostGPT********
Feature: Credential Wallet API
  As a user of the Credential Wallet API
  I want to be able to perform CRUD operations on accounts
  So that I can manage my account effectively

  Background:
    * def API_HOST_URL = 'http://localhost:8080'

  Scenario: Create my account
    * url API_HOST_URL
    * def accounts_body =
      """
      {
        "name": "John Doe",
        "email": "john.doe@example.com",
        "password": "SecurePass123!"
      }
      """
    Given path '/accounts'
    And request accounts_body
    When method POST
    Then status 201
    And match response == '#object'
    And match response.id == '#present'
    And match response.name == accounts_body.name
    And match response.email == accounts_body.email

  Scenario: Verify my account details
    * url API_HOST_URL
    Given path '/me'
    When method GET
    Then status 200
    And match response == '#object'
    And match response.id == '#present'
    And match response.name == 'John Doe'
    And match response.email == 'john.doe@example.com'
