# ********RoostGPT********

# Test generated by RoostGPT for test pw-it-Karate-1760081855381 using AI Type AWS Bedrock Runtime AI and AI Model us.anthropic.claude-3-7-sonnet-20250219-v1:0
# 
# ROOST_METHOD_HASH=ddde0fadad
# ROOST_METHOD_SIG_HASH=038bdcdfb9
# 
#  ########## Scenario ########## 
# 
# {
#   feature: 'Feature: Credential Wallet API\r\n' +
#     '  As a user of the Credential Wallet API\r\n' +
#     '  I want to be able to perform CRUD operations on accounts\r\n' +
#     '  So that I can manage my account effectively',
#   background: 'Background:\r\n    Given the base URL is "http://localhost:8080"',
#   rule: null,
#   scenario: {
#     title: 'Scenario: Delete authorization',
#     steps: 'Given authorization ID\r\n' +
#       'When the client sends a DELETE request to "/authorizations/ID"\r\n' +
#       'Then the response status code should be 200 for a successful delete\r\n' +
#       'And the authorizations should not appear in GET request for "/authorizations"',
#     examples: ''
#   }
# }
# 

# ********RoostGPT********
Feature: Credential Wallet API
  As a user of the Credential Wallet API
  I want to be able to perform CRUD operations on accounts
  So that I can manage my account effectively

  Background:
    * url 'http://localhost:8080'

  Scenario: Delete authorization
    Given def authorizationId = '12345'
    When path '/authorizations/' + authorizationId
    And method DELETE
    Then status 200
    Given path '/authorizations'
    When method GET
    Then status 200
    And match response !contains { id: '#(authorizationId)' }
    And match response == '#array'
