# ********RoostGPT********

# Test generated by RoostGPT for test pw-api-pytest-github-claude-1770783934966 using AI Type Claude AI and AI Model claude-sonnet-4-20250514
# 
# Test file generated for /employees_get for http method type GET 
# RoostTestHash=48e4dd6cd8
# 
# 

# ********RoostGPT********
"""
Employee API Test Suite

Execute with: pytest test_employees.py -v
For smoke tests only: pytest test_employees.py -m smoke -v
"""

import pytest
from pathlib import Path
from validator import SwaggerSchemaValidator

# Module-level constants
_ENDPOINT = "/employees"
_METHOD = "get"
_TEST_DATA_FILE = "employees.json"
_here = Path(__file__).resolve().parent
_endpoint_data_path = _here / _TEST_DATA_FILE
API_SPEC_PATH = _here / "api.json"


@pytest.fixture(scope="module")
def validator():
    """Initialize schema validator with API spec"""
    return SwaggerSchemaValidator(str(API_SPEC_PATH))


class TestEmployeesEndpoint:
    """Test suite for /employees endpoint"""

    @pytest.mark.smoke
    def test_get_employees_success_scenarios(self, api_client, merged_test_data, validator):
        """Test successful employee search scenarios"""
        data = merged_test_data(_endpoint_data_path)
        
        # Filter for success scenarios only
        success_scenarios = [item for item in data if item.get("statusCode") == 200]
        
        assert success_scenarios, "No success scenarios found in test data"
        
        for scenario in success_scenarios:
            search_string = scenario.get("searchString")
            expected_status = scenario["statusCode"]
            scenario_name = scenario.get("scenario", "Unknown scenario")
            
            # Prepare query parameters
            params = {}
            if search_string:
                params["searchString"] = search_string
            
            # Make API request
            response = api_client.get(_ENDPOINT, params=params)
            
            # Assert status code
            assert response.status_code == expected_status, (
                f"Scenario '{scenario_name}': Expected status {expected_status}, "
                f"got {response.status_code}. Response: {response.text}"
            )
            
            # Validate response schema
            validation_result = validator.validate_schema_by_response(
                _ENDPOINT, _METHOD, str(response.status_code), response
            )
            assert validation_result["valid"], (
                f"Scenario '{scenario_name}': Schema validation failed: "
                f"{validation_result.get('message', 'Unknown error')}"
            )
            
            # Validate response structure for 200 responses
            if response.status_code == 200:
                response_data = response.json()
                assert isinstance(response_data, list), (
                    f"Scenario '{scenario_name}': Expected array response, got {type(response_data)}"
                )
                
                # Validate required fields in each employee object
                for employee in response_data:
                    assert "jobTitle" in employee, (
                        f"Scenario '{scenario_name}': Missing required field 'jobTitle'"
                    )
                    assert "name" in employee, (
                        f"Scenario '{scenario_name}': Missing required field 'name'"
                    )
                    assert "email" in employee, (
                        f"Scenario '{scenario_name}': Missing required field 'email'"
                    )

    def test_get_employees_error_scenarios(self, api_client, validator):
        """Test error scenarios for employee search"""
        # Test with invalid search parameters that should return 400
        invalid_params = [
            {"searchString": ""},  # Empty search string
            {"searchString": " " * 1000},  # Very long search string
        ]
        
        for params in invalid_params:
            response = api_client.get(_ENDPOINT, params=params)
            
            # Should handle gracefully (either 200 with empty results or 400)
            assert response.status_code in [200, 400], (
                f"Unexpected status code {response.status_code} for params {params}. "
                f"Response: {response.text}"
            )
            
            # Validate response schema if defined
            validation_result = validator.validate_schema_by_response(
                _ENDPOINT, _METHOD, str(response.status_code), response
            )
            if validation_result.get("message") != "No response block for " + str(response.status_code):
                assert validation_result["valid"], (
                    f"Schema validation failed for params {params}: "
                    f"{validation_result.get('message', 'Unknown error')}"
                )

    def test_get_employees_no_params(self, api_client, validator):
        """Test employee search without any parameters"""
        response = api_client.get(_ENDPOINT)
        
        # Should return 200 with all employees
        assert response.status_code == 200, (
            f"Expected status 200, got {response.status_code}. Response: {response.text}"
        )
        
        # Validate response schema
        validation_result = validator.validate_schema_by_response(
            _ENDPOINT, _METHOD, str(response.status_code), response
        )
        assert validation_result["valid"], (
            f"Schema validation failed: {validation_result.get('message', 'Unknown error')}"
        )
        
        # Validate response structure
        response_data = response.json()
        assert isinstance(response_data, list), (
            f"Expected array response, got {type(response_data)}"
        )

    def test_get_employees_boundary_cases(self, api_client, validator):
        """Test boundary cases for employee search"""
        boundary_cases = [
            {"searchString": "a"},  # Single character
            {"searchString": "123"},  # Numeric string
            {"searchString": "!@#$%"},  # Special characters
            {"searchString": "nonexistent_role_xyz"},  # Non-existent search term
        ]
        
        for params in boundary_cases:
            response = api_client.get(_ENDPOINT, params=params)
            
            # Should handle gracefully
            assert response.status_code in [200, 400], (
                f"Unexpected status code {response.status_code} for boundary case {params}. "
                f"Response: {response.text}"
            )
            
            if response.status_code == 200:
                response_data = response.json()
                assert isinstance(response_data, list), (
                    f"Expected array response for boundary case {params}, got {type(response_data)}"
                )
