# ********RoostGPT********

# Test generated by RoostGPT for test pw-api-pytest-github-claude-1773396388743 using AI Type Open AI and AI Model gpt-4
# 
# Test file generated for /employees/{id}_get for http method type GET 
# RoostTestHash=0a005b8a0e
# 
# 

# ********RoostGPT********
import pytest
from validator import SwaggerSchemaValidator
from pathlib import Path

# Define module-level variables
_ENDPOINT = "/employees/{id}"
_METHOD = "get"
_TEST_DATA_FILE = "employees_id.json"
_here = Path(__file__).resolve().parent
_endpoint_data_path = _here / _TEST_DATA_FILE

# Initialize SwaggerSchemaValidator
API_SPEC_PATH = Path(__file__).parent / "api.json"
validator = SwaggerSchemaValidator(str(API_SPEC_PATH))

# Define test function
def test_get_employee_by_id(api_client, merged_test_data, get_config):
    # Load test data
    data = merged_test_data(_endpoint_data_path)

    for test_case in data:
        # Prepare request
        endpoint = _ENDPOINT.format(id=test_case["id"])
        headers = {"Authorization": f"Bearer {get_config('auth.token')}"}

        # Validate request
        request_validation = validator.validate_json(
            {"id": test_case["id"]}, 
            "getEmployeeById"
        )
        assert request_validation["valid"], request_validation.get("message")

        # Send request
        response = api_client.get(endpoint, headers=headers)

        # Validate response
        response_validation = validator.validate_schema_by_response(
            _ENDPOINT, 
            _METHOD, 
            str(response.status_code), 
            response
        )
        assert response_validation["valid"], response_validation.get("message")

        # Assert response status code
        assert response.status_code == test_case["statusCode"], f"Expected status code {test_case['statusCode']}, but got {response.status_code}"

        # Assert response body
        response_body = response.json()
        assert "id" in response_body, "Response body does not contain 'id'"
        assert "jobTitle" in response_body, "Response body does not contain 'jobTitle'"
        assert "name" in response_body, "Response body does not contain 'name'"
        assert "email" in response_body, "Response body does not contain 'email'"
