# ********RoostGPT********

# Test generated by RoostGPT for test pw-api-pytest-github-azure-1776917879057 using AI Type Azure Open AI and AI Model gpt-4.1
# 
# Test file generated for /employees/{id}_get for http method type GET 
# RoostTestHash=0a005b8a0e
# 
# 

# ********RoostGPT********
"""
pytest module: Tests for GET /employees/{id}.

- Reads endpoint-specific data from employees_id.json
- Uses fixtures defined in conftest.py for API client/config
- Schema validation via SwaggerSchemaValidator (from validator.py)
- All flow/test data comes from config and merged_test_data fixture (NEVER hardcoded).
- Execute: pytest -v test_employees_id.py

To run smoke tests only:
    pytest -m smoke -v test_employees_id.py

Requires:
  - config.yml in same directory (see README/config docs)
  - employees_id.json in same directory
  - validator.py in PYTHONPATH (see root validator.py)
"""
import pytest
from pathlib import Path

from validator import SwaggerSchemaValidator

_ENDPOINT = "/employees/{id}"
_METHOD = "get"
_TEST_DATA_FILE = "employees_id.json"
_here = Path(__file__).resolve().parent
_endpoint_data_path = _here / _TEST_DATA_FILE
_API_SPEC_PATH = _here / "api.json"


@pytest.fixture(scope="module")
def validator():
    return SwaggerSchemaValidator(str(_API_SPEC_PATH))


@pytest.mark.smoke
def test_get_employee_by_id_successful(api_client, config, merged_test_data, validator):
    """
    Smoke: GET /employees/{id} - 200 OK response and response schema validation.
    """
    test_data = merged_test_data(_endpoint_data_path)
    for entry in test_data:
        # Only test successful scenarios (statusCode == 200)
        if entry.get("statusCode") != 200:
            continue

        # Path param: take from test data, fallback to config if present
        emp_id = entry.get("id") or config.get("test_data", {}).get("id")
        assert emp_id, "Employee id not specified in test case or config"

        endpoint = _ENDPOINT.replace("{id}", emp_id)
        response = api_client.get(endpoint)

        # Assert status code matches expected
        assert response.status_code == entry["statusCode"], (
            f"Expected {entry['statusCode']} for id={emp_id}, got {response.status_code}"
        )

        # Validate JSON schema of response using validator
        result = validator.validate_schema_by_response(
            "/employees/{id}", _METHOD, "200", response
        )
        assert result["valid"], f"Schema validation failed: {result.get('message', '')}"

        # Verify required fields in response
        resp_json = response.json()
        for req_field in ("jobTitle", "name", "email"):
            assert req_field in resp_json, f"Missing required field '{req_field}' in response for id={emp_id}"

        # Check data fields match test input (sanity-check only, does not enforce *all* fields must be returned)
        for key in ("id", "jobTitle", "name", "email"):
            expected = entry.get(key)
            if expected is not None:
                assert resp_json.get(key) == expected, (
                    f"Response field '{key}' mismatch: expected {expected}, got {resp_json.get(key)}"
                )


def test_get_employee_by_id_not_found(api_client, config, merged_test_data, validator):
    """
    GET /employees/{id} - 404 Not Found for invalid/nonexistent id.
    """
    test_data = merged_test_data(_endpoint_data_path)

    # Test negative/boundary: use an ID known to be missing (not in happy path test data)
    existing_ids = {str(entry.get("id")) for entry in test_data if "id" in entry}
    # Try with a sure miss (UUID with all 0s)
    missing_id = "00000000-0000-0000-0000-000000000000"
    if missing_id in existing_ids:
        # Find any other unused string (for robustness)
        import uuid
        attempts = 0
        while missing_id in existing_ids and attempts < 10:
            missing_id = str(uuid.uuid4())
            attempts += 1

    endpoint = _ENDPOINT.replace("{id}", missing_id)
    response = api_client.get(endpoint)
    # OpenAPI 404 defined
    assert response.status_code == 404, (
        f"Expected 404 for non-existent id, got {response.status_code}"
    )

    # Validate schema if defined for 404; otherwise, assert content is empty or error-focused
    result = validator.validate_schema_by_response("/employees/{id}", _METHOD, "404", response)
    # If schema present, will return valid: True, else may return "No schema defined for..."
    assert result["valid"], (
        f"Schema validation for 404 response failed: {result.get('message','')}"
    )
