# ********RoostGPT********

# Test generated by RoostGPT for test pw-api-pytest-github-claude-1768104632173 using AI Type Claude AI and AI Model claude-sonnet-4-20250514
# 
# Test file generated for /employees/{id}_get for http method type GET 
# RoostTestHash=0a005b8a0e
# 
# 

# ********RoostGPT********
"""
Employee API Test Suite

Tests for the /employees/{id} endpoint.

To run these tests:
    pytest test_employees_id.py -v
    pytest test_employees_id.py::test_get_employee_by_id -v
    pytest -m smoke test_employees_id.py
"""

import pytest
from pathlib import Path
from validator import SwaggerSchemaValidator

# Module-level constants
_ENDPOINT = "/employees/{id}"
_METHOD = "get"
_TEST_DATA_FILE = "employees_id.json"
_here = Path(__file__).resolve().parent
_endpoint_data_path = _here / _TEST_DATA_FILE
API_SPEC_PATH = _here / "api.json"


@pytest.fixture(scope="module")
def validator():
    """Initialize schema validator with API specification"""
    return SwaggerSchemaValidator(str(API_SPEC_PATH))


@pytest.mark.smoke
def test_get_employee_by_id_success(api_client, config, merged_test_data, validator):
    """Test successful retrieval of employee by ID"""
    # Load test data from endpoint JSON file
    data = merged_test_data(_endpoint_data_path)
    
    # Iterate over all test scenarios from JSON
    for test_case in data:
        employee_id = test_case.get("id")
        expected_status = test_case.get("statusCode", 200)
        scenario = test_case.get("scenario", "Unknown scenario")
        
        # Skip if no ID provided
        if not employee_id:
            continue
            
        # Construct endpoint with ID parameter
        endpoint = f"/employees/{employee_id}"
        
        # Make API request
        response = api_client.get(endpoint)
        
        # Assert status code
        assert response.status_code == expected_status, (
            f"Expected status {expected_status} but got {response.status_code} "
            f"for scenario: {scenario}"
        )
        
        # Validate response schema for successful responses
        if response.status_code == 200:
            validation_result = validator.validate_schema_by_response(
                _ENDPOINT, _METHOD, str(response.status_code), response
            )
            assert validation_result["valid"], (
                f"Response schema validation failed: {validation_result.get('message', 'Unknown error')}"
            )
            
            # Validate required fields are present
            response_data = response.json()
            required_fields = ["jobTitle", "name", "email"]
            
            for field in required_fields:
                assert field in response_data, (
                    f"Required field '{field}' missing from response for scenario: {scenario}"
                )
                assert response_data[field] is not None, (
                    f"Required field '{field}' is null for scenario: {scenario}"
                )


def test_get_employee_by_id_not_found(api_client, validator):
    """Test employee not found scenario"""
    # Use a non-existent UUID
    non_existent_id = "00000000-0000-0000-0000-000000000000"
    endpoint = f"/employees/{non_existent_id}"
    
    response = api_client.get(endpoint)
    
    # Assert 404 status code
    assert response.status_code == 404, (
        f"Expected status 404 but got {response.status_code} for non-existent employee"
    )
    
    # Validate response schema
    validation_result = validator.validate_schema_by_response(
        _ENDPOINT, _METHOD, str(response.status_code), response
    )
    assert validation_result["valid"], (
        f"404 response schema validation failed: {validation_result.get('message', 'Unknown error')}"
    )


def test_get_employee_by_id_invalid_uuid_format(api_client):
    """Test invalid UUID format handling"""
    invalid_ids = [
        "invalid-uuid",
        "123",
        "not-a-uuid-at-all",
        ""
    ]
    
    for invalid_id in invalid_ids:
        endpoint = f"/employees/{invalid_id}"
        response = api_client.get(endpoint)
        
        # Should return 400 or 404 for invalid UUID format
        assert response.status_code in [400, 404], (
            f"Expected status 400 or 404 but got {response.status_code} "
            f"for invalid UUID: {invalid_id}"
        )


def test_get_employee_by_id_boundary_cases(api_client):
    """Test boundary cases for employee ID parameter"""
    # Test with maximum length UUID
    max_uuid = "ffffffff-ffff-ffff-ffff-ffffffffffff"
    endpoint = f"/employees/{max_uuid}"
    
    response = api_client.get(endpoint)
    
    # Should handle gracefully (200 if exists, 404 if not)
    assert response.status_code in [200, 404], (
        f"Expected status 200 or 404 but got {response.status_code} "
        f"for boundary UUID: {max_uuid}"
    )
    
    # Test with minimum UUID
    min_uuid = "00000000-0000-0000-0000-000000000000"
    endpoint = f"/employees/{min_uuid}"
    
    response = api_client.get(endpoint)
    
    assert response.status_code in [200, 404], (
        f"Expected status 200 or 404 but got {response.status_code} "
        f"for boundary UUID: {min_uuid}"
    )
