# ********RoostGPT********

# Test generated by RoostGPT for test pw-api-pytest-github-azure-1778044170764 using AI Type Azure Open AI and AI Model gpt-4.1
# 
# Test file generated for /employees_post for http method type POST 
# RoostTestHash=e5b9d8d67f
# 
# 

# ********RoostGPT********
"""
Pytest test suite for the Employee API (/employees POST endpoint).

- Loads test cases dynamically from endpoint-level JSON.
- Uses merged test data fixture to supply payloads.
- Validates all request and response data against OpenAPI schema (via SwaggerSchemaValidator).
- No authentication is performed (endpoint is unsecured per API spec).
- All test helpers and configuration come from conftest.py/config.yml.

How to execute:
    pytest tests/test_post_employees.py
"""

import pytest
import requests
from pathlib import Path

from validator import SwaggerSchemaValidator

_ENDPOINT = "/employees"
_METHOD = "post"
_TEST_DATA_FILE = "employees.json"
_here = Path(__file__).resolve().parent
_endpoint_data_path = _here / _TEST_DATA_FILE
_API_SPEC_PATH = _here.parent / "api.json"

@pytest.fixture(scope="module")
def validator():
    return SwaggerSchemaValidator(str(_API_SPEC_PATH))


@pytest.mark.smoke
def test_post_employees_success(api_client, merged_test_data, validator):
    """
    Happy-path: Only required fields are provided; endpoint returns 201.
    """
    data = merged_test_data(_endpoint_data_path)
    test_cases = [tc for tc in data if tc.get("statusCode") == 201]

    for case in test_cases:
        # Construct request payload with only required fields (if present)
        payload = {}
        # Always check endpoint test data for possible override
        for field in ("jobTitle", "name", "email"):
            if field in case:
                payload[field] = case[field]
        # If not explicitly in the endpoint case, try config default
        if not payload.get("jobTitle"):
            continue  # cannot run smoke test without required field
        if not payload.get("name"):
            continue
        if not payload.get("email"):
            continue

        # Validate payload schema before call, raise immediately on error
        req_val_res = validator.validate_json(payload, schema_name="addEmployee_request") \
            if "addEmployee_request" in getattr(validator, "schemas", {}) \
            else validator.validate_json(payload, schema_name="Employee")
        assert req_val_res["valid"], \
            f"Request did not match schema for Employee: {req_val_res.get('message')}"

        response = api_client.post(_ENDPOINT, json=payload)
        assert response.status_code == 201, \
            f"Expected 201 for successful create. Got {response.status_code}: {getattr(response, 'text', '')}"

        # Validate response (no schema, but still check with validator utility: must not error)
        val = validator.validate_schema_by_response(_ENDPOINT, _METHOD, "201", response)
        assert val["valid"], f"Response failed schema validation (201): {val.get('message')}"


def test_post_employees_cases(api_client, merged_test_data, validator):
    """
    Covers all POST /employees cases in endpoint test data.
    """
    data = merged_test_data(_endpoint_data_path)
    for idx, case in enumerate(data):
        payload = {}

        # Compose request payload from test data, with endpoint file taking precedence
        for field in ("id", "jobTitle", "name", "email"):
            if field in case:
                payload[field] = case[field]

        # Fall back to config.yml test_data for any missing field (except required for error case)
        # However, since config only supplies 'id', others would not be filled except by endpoint test data

        # Determine expected code and scenario
        expected_status = case.get("statusCode")
        scenario = case.get("scenario", "")

        # Validate request payload schema, should pass if it's meant to be accepted, else may fail
        req_val_res = validator.validate_json(payload, schema_name="addEmployee_request") \
            if "addEmployee_request" in getattr(validator, "schemas", {}) \
            else validator.validate_json(payload, schema_name="Employee")

        # If scenario is positive and expected is 201, payload must satisfy required fields
        if expected_status == 201:
            assert req_val_res["valid"], f"SCENARIO {idx}: Required fields missing/invalid: {req_val_res.get('message')}"

        # Actually make the call
        try:
            response = api_client.post(_ENDPOINT, json=payload)
        except requests.RequestException as e:
            pytest.fail(f"SCENARIO {idx}: API client error: {e}")

        assert response.status_code == expected_status, \
            f"SCENARIO {idx}, Scenario '{scenario}': Expected status {expected_status}, got {response.status_code}"

        # Validate response schema where possible
        val = validator.validate_schema_by_response(_ENDPOINT, _METHOD, str(expected_status), response)
        assert val["valid"], f"SCENARIO {idx}: Response failed schema validation ({expected_status}): {val.get('message')}"

