// ********RoostGPT********
/*
Test generated by RoostGPT for test restAssuredJsonTest using AI Type Azure Open AI and AI Model roostgpt-4-32k

Test generated for /deeplink_post for http method type POST in rest-assured framework

RoostTestHash=becedd7344

[
  {
    "ScenarioID": "1",
    "TestName": "testValidRequestReturns200",
    "Description": "Test a valid POST request with all required headers and proper values",
    "Execution": {
      "Arrange": "Prepare headers: Authorization='Bearer valid_token', koreUserId='12345', botId='bot123', accountId='acc123', tenantId='tenant123', environment='prod', channel='web'",
      "Act": "Send POST request to /deeplink with correct headers",
      "Assert": "Check for 200 status and response body contains a non-empty list of deeplinks"
    },
    "Validation": "Ensures API successfully returns response with valid input"
  },
  {
    "ScenarioID": "2",
    "TestName": "testMissingAuthorizationHeaderReturns401",
    "Description": "Test API returns 401 when Authorization header is missing",
    "Execution": {
      "Arrange": "Prepare headers: koreUserId='12345', botId='bot123', accountId='acc123', tenantId='tenant123', environment='prod', channel='web' with no Authorization header",
      "Act": "Send POST request to /deeplink with missing Authorization header",
      "Assert": "Check for 401 status and error message with authorization failure"
    },
    "Validation": "Ensures API rejects requests without Authorization header"
  },
  {
    "ScenarioID": "3",
    "TestName": "testInvalidTokenReturns401",
    "Description": "Test API returns 401 when Authorization token is invalid",
    "Execution": {
      "Arrange": "Prepare headers: Authorization='Bearer invalid_token', koreUserId='12345', botId='bot123', accountId='acc123', tenantId='tenant123', environment='prod', channel='web'",
      "Act": "Send POST request to /deeplink with invalid Authorization token",
      "Assert": "Check for 401 status and error message with authorization failure"
    },
    "Validation": "Ensures API rejects unauthorized access attempts"
  },
  {
    "ScenarioID": "4",
    "TestName": "testEmptyHeaderValuesReturns200",
    "Description": "Test API returns 200 when optional headers are provided with empty values",
    "Execution": {
      "Arrange": "Prepare headers: Authorization='Bearer valid_token', koreUserId='', botId='', accountId='', tenantId='', environment='', channel=''",
      "Act": "Send POST request to /deeplink with empty values for optional headers",
      "Assert": "Check for 200 status and response body contains a list of deeplinks"
    },
    "Validation": "Ensures optional headers are handled gracefully"
  },
  {
    "ScenarioID": "5",
    "TestName": "testHeaderMissingReturns200",
    "Description": "Test API returns 200 when optional headers are completely omitted",
    "Execution": {
      "Arrange": "Prepare headers: Authorization='Bearer valid_token' and omit all optional headers",
      "Act": "Send POST request to /deeplink with Authorization header only",
      "Assert": "Check for 200 status and response body contains a list of deeplinks"
    },
    "Validation": "Confirms optional headers are not mandatory for a valid response"
  },
  {
    "ScenarioID": "6",
    "TestName": "testInvalidEnvironmentValueReturns404",
    "Description": "Test API returns 404 when invalid environment value is sent in the header",
    "Execution": {
      "Arrange": "Prepare headers: Authorization='Bearer valid_token', koreUserId='12345', botId='bot123', accountId='acc123', tenantId='tenant123', environment='invalid_env', channel='web'",
      "Act": "Send POST request to /deeplink with invalid environment value",
      "Assert": "Check for 404 status and error message indicating not found"
    },
    "Validation": "Ensures API properly handles invalid environment values"
  },
  {
    "ScenarioID": "7",
    "TestName": "testCorrectEnumValuesInResponse",
    "Description": "Test API responses contain correct enum values for linkType",
    "Execution": {
      "Arrange": "Prepare headers: Authorization='Bearer valid_token', koreUserId='12345', botId='bot123', accountId='acc123', tenantId='tenant123', environment='prod', channel='web'",
      "Act": "Send POST request to /deeplink with correct headers",
      "Assert": "Check linkType values in the response are within the allowed enum values (deeplink, weburl, internalurl)"
    },
    "Validation": "Verifies enumerated values for linkType are constrained to specified allowed values"
  },
  {
    "ScenarioID": "8",
    "TestName": "testMalformedAuthorizationHeaderReturns401",
    "Description": "Test API returns 401 when Authorization header is malformed",
    "Execution": {
      "Arrange": "Prepare headers: Authorization='invalid_header_format', koreUserId='12345', botId='bot123', accountId='acc123', tenantId='tenant123', environment='prod', channel='web'",
      "Act": "Send POST request to /deeplink with malformed Authorization header",
      "Assert": "Check for 401 status and error message indicating authorization failure"
    },
    "Validation": "Ensures API rejects malformed Authorization headers"
  },
  {
    "ScenarioID": "9",
    "TestName": "testNullValuesInHeadersReturns200",
    "Description": "Test API response when headers contain null values",
    "Execution": {
      "Arrange": "Prepare headers: Authorization='Bearer valid_token', koreUserId=null, botId=null, accountId=null, tenantId=null, environment='prod', channel='web'",
      "Act": "Send POST request to /deeplink with null values for optional headers",
      "Assert": "Check for 200 status and response body contains a list of deeplinks"
    },
    "Validation": "Verifies null values in optional headers are accepted"
  },
  {
    "ScenarioID": "10",
    "TestName": "testNoHeadersProvidedReturns401",
    "Description": "Test API returns 401 when no headers are provided",
    "Execution": {
      "Arrange": "Do not provide any headers",
      "Act": "Send POST request to /deeplink with no headers",
      "Assert": "Check for 401 status and error message indicating authorization failure"
    },
    "Validation": "Ensures API rejects requests lacking required Authorization headers"
  },
  {
    "ScenarioID": "11",
    "TestName": "testEmptyResponseForInvalidEnvironmentReturns404",
    "Description": "Test API returns empty response and 404 for invalid environment values",
    "Execution": {
      "Arrange": "Prepare headers: Authorization='Bearer valid_token', koreUserId='12345', botId='bot123', accountId='acc123', tenantId='tenant123', environment='test_invalid', channel='web'",
      "Act": "Send POST request to /deeplink with invalid environment value",
      "Assert": "Check for 404 status and error message indicating not found"
    },
    "Validation": "Confirms invalid environment values return a 404 response"
  }
]

*/

// ********RoostGPT********
package org.springframework.RoostTest;

import org.json.JSONObject;
import org.json.JSONArray;
import io.restassured.RestAssured;
import io.restassured.response.Response;
import io.restassured.path.json.JsonPath;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import java.util.*;
import static io.restassured.RestAssured.given;
import static org.hamcrest.Matchers.*;
import org.hamcrest.MatcherAssert;

public class DeeplinkPostTest {

    List<JSONObject> testCases = new ArrayList<>();

    @BeforeEach
    public void setUp() {
        TestdataLoader dataloader = new TestdataLoader();
        testCases = dataloader.loadJson("src/test/java/org/springframework/RoostTest/deeplinkPostTest.JSON");
    }


    @Test
    public void DeeplinkPost_Test() {
        this.setUp();
        Integer testNumber = 1;
        for (JSONObject testData : testCases) {
            RestAssured.baseURI = "https://localhost:8080/smt";

            JSONObject requestHeader = testData.optJSONObject("request_header");
            JSONObject requestBody = testData.optJSONObject("request_body");
            JSONObject queryParams = testData.optJSONObject("query_params");
            JSONObject pathParams = testData.optJSONObject("path_params");
            String requestPath = "/deeplink";

            if (pathParams != null) {
                for (String key : pathParams.keySet()) {
                    requestPath = requestPath.replace("{" + key + "}", pathParams.getString(key));
                }
            }

            io.restassured.specification.RequestSpecification req = given();

            // Resolve Authorization token priority: ENV > Param(RoostENV) > JSON
            String userEnvAuthToken = System.getenv("AUTH_TOKEN");
            String resolvedAuthToken = (userEnvAuthToken != null && !userEnvAuthToken.isEmpty()) ? userEnvAuthToken : "credential-register/swagger_server/swagger/swagger.yaml";

            boolean authSet = false;
            if (requestHeader != null) {
                Iterator<String> keys = requestHeader.keys();
                while (keys.hasNext()) {
                    String key = keys.next();
                    String value = requestHeader.getString(key);

                    if (key.equalsIgnoreCase("Authorization")) {
                        if (value.equalsIgnoreCase("${AUTH_TOKEN}") && resolvedAuthToken != null && !resolvedAuthToken.isEmpty()) {
                            req.header("Authorization", "Bearer " + resolvedAuthToken);
                            authSet = true;
                        } else {
                            req.header(key, value);
                            authSet = true;
                        }
                    } else {
                        req.header(key, value);
                    }
                }
            }

            if (!authSet && resolvedAuthToken != null && !resolvedAuthToken.isEmpty()) {
                req.header("Authorization", "Bearer " + resolvedAuthToken);
            }

            if (queryParams != null) {
                for (String key : queryParams.keySet()) {
                    req.queryParam(key, queryParams.get(key));
                }
            }

            if (requestBody != null && requestBody.length() > 0) {
                req.body(requestBody.toString());
            }

            Response responseObj;
            switch ("post".toLowerCase()) {
              case "post":
                responseObj = req.when().post(requestPath);
                break;
              case "get":
                responseObj = req.when().get(requestPath);
                break;
              case "put":
                responseObj = req.when().put(requestPath);
                break;
              case "delete":
                responseObj = req.when().delete(requestPath);
                break;
              default:
                throw new RuntimeException("Unsupported HTTP method: " + "post");
            }

            responseObj = responseObj.then().extract().response();

            System.out.printf("Test Case %d: DeeplinkPost_Test\n", testNumber++);
            System.out.println("Request: POST " + requestPath);
            System.out.println("Status Code: " + responseObj.statusCode());

            if (testData.has("expected_status_code")) {
                int expectedCode = testData.getInt("expected_status_code");
                MatcherAssert.assertThat(
                    "Expected status code " + expectedCode + " but got " + responseObj.statusCode(),
                    responseObj.statusCode(),
                    equalTo(expectedCode)
                );
            }
        }
    }
}
