// ********RoostGPT********
/*
Test generated by RoostGPT for test pw-test-1746596242486 using AI Type Open AI and AI Model gpt-4

Test generated for /GetCustomerInfo_post for http method type POST in rest-assured framework

RoostTestHash=735d04cab5


*/

// ********RoostGPT********
package org.springframework.RoostTest;
import io.restassured.RestAssured;
import io.restassured.path.json.JsonPath;
import io.restassured.http.ContentType;
import io.restassured.response.Response;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static io.restassured.RestAssured.given;
import java.io.BufferedReader;
import java.io.File;
import java.io.IOException;
import java.util.HashMap;
import java.util.Map;
import java.util.ArrayList;
import java.util.List;
import org.hamcrest.MatcherAssert;
import static org.hamcrest.Matchers.*;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.json.JSONObject;
import org.json.XML;
import org.json.JSONException;
import org.json.JSONArray;
import java.util.Arrays;

public class getCustomerInfoPostTest {

    List<Map<String, String>> envList = new ArrayList<>();


    @BeforeEach
    public void setUp() {
      TestdataLoader dataloader = new TestdataLoader();
      String[] envVarsList = {""};
      envList = dataloader.load("src/test/java/org/springframework/RoostTest/GetCustomerInfoPostTest.csv", envVarsList);
    }

  
    @Test  
    public void getCustomerInfoPost_Test() throws JSONException {
        this.setUp();
        Integer testNumber = 1;
        for (Map<String, String> testData : envList) {
          RestAssured.baseURI = (testData.get("BASE_URL") != null && !testData.get("BASE_URL").isEmpty()) ? testData.get("BASE_URL"): "https://localhost:8080/smt";  
          JSONObject requestBodyObject = new JSONObject();
          if(testData.get("RequestBody") != null){
              requestBodyObject = new JSONObject(testData.get("RequestBody"));
          }
                Response responseObj = given()
				.header("koreUserId", testData.get("koreUserId") != null ? testData.get("koreUserId") : "")
				.header("botId", testData.get("botId") != null ? testData.get("botId") : "")
				.header("accountId", testData.get("accountId") != null ? testData.get("accountId") : "")
				.header("Authorization", testData.get("Authorization") != null ? testData.get("Authorization") : "")
				.header("X_Auth_token", testData.get("X_Auth_token") != null ? testData.get("X_Auth_token") : "")
				.header("X_CORRELATION_ID", testData.get("X_CORRELATION_ID") != null ? testData.get("X_CORRELATION_ID") : "")
				.contentType(ContentType.JSON)
				.body(requestBodyObject.toString())
                .when()
                .post("/GetCustomerInfo")  
                .then() 
                .extract().response(); 
              JsonPath response;
              String contentType = responseObj.getContentType();

              System.out.printf("Test Case %d: getCustomerInfoPost_Test \n", testNumber++);
              System.out.println("Request: POST /GetCustomerInfo");
              System.out.println("Status Code: " + responseObj.statusCode());
              if (testData.get("statusCode") != null) {
                String statusCodeFromCSV = testData.get("statusCode");
                if (statusCodeFromCSV.contains("X")) {
                  MatcherAssert.assertThat(
                      "Expected a status code of category " + statusCodeFromCSV + ", but got "
                          + Integer.toString(responseObj.statusCode()) + " instead",
                      Integer.toString(responseObj.statusCode()).charAt(0), equalTo(statusCodeFromCSV.charAt(0)));
                } else {
                  MatcherAssert.assertThat(
                      Integer.toString(responseObj.statusCode()), equalTo(statusCodeFromCSV));
                }
              } 
              				else {  
      List<Integer> expectedStatusCodes = Arrays.asList(200,401,404);
				MatcherAssert.assertThat(responseObj.statusCode(), is(in(expectedStatusCodes)));
          }
				String stringifiedStatusCode = Integer.toString(responseObj.statusCode());
        switch(responseObj.statusCode()){
        
          case 200:
            stringifiedStatusCode = "200";
            MatcherAssert.assertThat(contentType, equalTo("application/json"));
            break;
         
          case 401:
            stringifiedStatusCode = "401";
            MatcherAssert.assertThat(contentType, equalTo("application/json"));
            break;
         
          case 404:
            stringifiedStatusCode = "404";
            MatcherAssert.assertThat(contentType, equalTo("application/json"));
            break;
         
    }

      switch(Integer.toString(responseObj.statusCode()).charAt(0)){
      
    }

      
              if (contentType.contains("application/xml") || contentType.contains("text/xml")) {
                String xmlResponse = responseObj.asString();
                JSONObject jsonResponse = XML.toJSONObject(xmlResponse);
                JSONObject jsonData = jsonResponse.getJSONObject("xml");
                String jsonString = jsonData.toString();
                response = new JsonPath(jsonString);
        
              } else if(contentType.contains("application/json")){  
                response = responseObj.jsonPath(); 
              } else {
                System.out.println("Response content type found: "+contentType+", but RoostGPT currently only supports the following response content types: application/json,text/xml,application/xml");
                continue;
              }
         
                if(stringifiedStatusCode.equals("200")){					System.out.println("Description: successful operation");
      
              if (response.get("alternatePhoneNumber") != null) {
                  
                MatcherAssert.assertThat(response.get("alternatePhoneNumber"), instanceOf(Integer.class));
              }
      
              if (response.get("customerId") != null) {
                  
                MatcherAssert.assertThat(response.get("customerId"), instanceOf(String.class));
              }
      
              if (response.get("email") != null) {
                  
                MatcherAssert.assertThat(response.get("email"), instanceOf(String.class));
              }
      
              if (response.get("identificationNumber") != null) {
                  
                MatcherAssert.assertThat(response.get("identificationNumber"), instanceOf(Integer.class));
              }
      
              if (response.get("identificationType") != null) {
                  
                MatcherAssert.assertThat(response.get("identificationType"), instanceOf(String.class));
              }
      
              if (response.get("image") != null) {
                  
                MatcherAssert.assertThat(response.get("image"), instanceOf(String.class));
              }
      
              if (response.get("isAlternateMobileNumber") != null) {
                  
                MatcherAssert.assertThat(response.get("isAlternateMobileNumber"), instanceOf(Boolean.class));
              }
      
              if (response.get("isPrimaryMobileNumber") != null) {
                  
                MatcherAssert.assertThat(response.get("isPrimaryMobileNumber"), instanceOf(Boolean.class));
              }
      
              if (response.get("location") != null) {
                  
                MatcherAssert.assertThat(response.get("location"), instanceOf(String.class));
              }
      
              if (response.get("name") != null) {
                  
                MatcherAssert.assertThat(response.get("name"), instanceOf(String.class));
              }
      
              if (response.get("firstName") != null) {
                  
                MatcherAssert.assertThat(response.get("firstName"), instanceOf(String.class));
              }
      
              if (response.get("lastName") != null) {
                  
                MatcherAssert.assertThat(response.get("lastName"), instanceOf(String.class));
              }
      
              if (response.get("personalBanker") != null) {
                      
              if (response.get("personalBanker.name") != null) {
                  
                MatcherAssert.assertThat(response.get("personalBanker.name"), instanceOf(String.class));
              }
      
              if (response.get("personalBanker.email") != null) {
                  
                MatcherAssert.assertThat(response.get("personalBanker.email"), instanceOf(String.class));
              }
      
              if (response.get("personalBanker.mobileNumber") != null) {
                  
                MatcherAssert.assertThat(response.get("personalBanker.mobileNumber"), instanceOf(String.class));
              }

              }
      
              if (response.get("phone") != null) {
                  
                MatcherAssert.assertThat(response.get("phone"), instanceOf(Integer.class));
              }
      
              if (response.get("securityQuestions") != null) {
                      
                for (int i = 0; i < response.getList("securityQuestions").size(); i++) {      
                  }    
                MatcherAssert.assertThat(response.getList("securityQuestions"), instanceOf(List.class));

              }
      
              if (response.get("segmentId") != null) {
                  
                MatcherAssert.assertThat(response.get("segmentId"), instanceOf(Integer.class));
              }
				}
if(stringifiedStatusCode.equals("401")){					System.out.println("Description: Error: Authorisation failed.");
      
              if (response.get("err") != null) {
                      
              if (response.get("err.message") != null) {
                  
                MatcherAssert.assertThat(response.get("err.message"), instanceOf(String.class));
              }

              }
				}
if(stringifiedStatusCode.equals("404")){					System.out.println("Description: Error: Not Found");
      
              if (response.get("err") != null) {
                      
              if (response.get("err.message") != null) {
                  
                MatcherAssert.assertThat(response.get("err.message"), instanceOf(String.class));
              }

              }
				}


            }  
    }
}
