// ********RoostGPT********
/*
Test generated by RoostGPT for test pw-test-1745560333451 using AI Type Azure Open AI and AI Model roostgpt-4-32k

Test generated by RoostGPT for test pw-test-1745560333451 using AI Type Azure Open AI and AI Model roostgpt-4-32k

Test generated for /locateProfile_post for http method type POST in rest-assured framework

RoostTestHash=309794f5ab


*/

// ********RoostGPT********
package org.springframework.RoostTest;
import io.restassured.RestAssured;
import io.restassured.path.json.JsonPath;
import io.restassured.http.ContentType;
import io.restassured.response.Response;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static io.restassured.RestAssured.given;
import java.io.BufferedReader;
import java.io.File;
import java.io.IOException;
import java.util.HashMap;
import java.util.Map;
import java.util.ArrayList;
import java.util.List;
import org.hamcrest.MatcherAssert;
import static org.hamcrest.Matchers.*;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.json.JSONObject;
import org.json.XML;
import org.json.JSONException;
import org.json.JSONArray;
import java.util.Arrays;

public class locateProfilePostTest {

    List<Map<String, String>> envList = new ArrayList<>();


    @BeforeEach
    public void setUp() {
      TestdataLoader dataloader = new TestdataLoader();
      String[] envVarsList = {""};
      envList = dataloader.load("src/test/java/org/springframework/RoostTest/locateProfilePostTest.csv", envVarsList);
    }

  
    @Test  
    public void locateProfilePost_Test() throws JSONException {
        this.setUp();
        Integer testNumber = 1;
        for (Map<String, String> testData : envList) {
          RestAssured.baseURI = (testData.get("BASE_URL") != null && !testData.get("BASE_URL").isEmpty()) ? testData.get("BASE_URL"): "https://localhost:8080/smt";  
          JSONObject requestBodyObject = new JSONObject();
          if(testData.get("RequestBody") != null){
              requestBodyObject = new JSONObject(testData.get("RequestBody"));
          }
                Response responseObj = given()
				.header("koreUserId", testData.get("koreUserId") != null ? testData.get("koreUserId") : "")
				.header("botId", testData.get("botId") != null ? testData.get("botId") : "")
				.header("accountId", testData.get("accountId") != null ? testData.get("accountId") : "")
				.header("Authorization", testData.get("Authorization") != null ? testData.get("Authorization") : "")
				.contentType(ContentType.JSON)
				.body(requestBodyObject.toString())
                .when()
                .post("/locateProfile")  
                .then() 
                .extract().response(); 
              JsonPath response;
              String contentType = responseObj.getContentType();

              System.out.printf("Test Case %d: locateProfilePost_Test \n", testNumber++);
              System.out.println("Request: POST /locateProfile");
              System.out.println("Status Code: " + responseObj.statusCode());
              if (testData.get("statusCode") != null) {
                String statusCodeFromCSV = testData.get("statusCode");
                if (statusCodeFromCSV.contains("X")) {
                  MatcherAssert.assertThat(
                      "Expected a status code of category " + statusCodeFromCSV + ", but got "
                          + Integer.toString(responseObj.statusCode()) + " instead",
                      Integer.toString(responseObj.statusCode()).charAt(0), equalTo(statusCodeFromCSV.charAt(0)));
                } else {
                  MatcherAssert.assertThat(
                      Integer.toString(responseObj.statusCode()), equalTo(statusCodeFromCSV));
                }
              } 
              				else {  
      List<Integer> expectedStatusCodes = Arrays.asList(200,401,404);
				MatcherAssert.assertThat(responseObj.statusCode(), is(in(expectedStatusCodes)));
          }
				String stringifiedStatusCode = Integer.toString(responseObj.statusCode());
        switch(responseObj.statusCode()){
        
          case 200:
            stringifiedStatusCode = "200";
            MatcherAssert.assertThat(contentType, equalTo("application/json"));
            break;
         
          case 401:
            stringifiedStatusCode = "401";
            MatcherAssert.assertThat(contentType, equalTo("application/json"));
            break;
         
          case 404:
            stringifiedStatusCode = "404";
            MatcherAssert.assertThat(contentType, equalTo("application/json"));
            break;
         
    }

      switch(Integer.toString(responseObj.statusCode()).charAt(0)){
      
    }

      
              if (contentType.contains("application/xml") || contentType.contains("text/xml")) {
                String xmlResponse = responseObj.asString();
                JSONObject jsonResponse = XML.toJSONObject(xmlResponse);
                JSONObject jsonData = jsonResponse.getJSONObject("xml");
                String jsonString = jsonData.toString();
                response = new JsonPath(jsonString);
        
              } else if(contentType.contains("application/json")){  
                response = responseObj.jsonPath(); 
              } else {
                System.out.println("Response content type found: "+contentType+", but RoostGPT currently only supports the following response content types: application/json,text/xml,application/xml");
                continue;
              }
         
                if(stringifiedStatusCode.equals("200")){					System.out.println("Description: success");
      
              if (response.get("accountNumber") != null) {
                  
                MatcherAssert.assertThat(response.get("accountNumber"), instanceOf(String.class));
              }
      
              if (response.get("cardDetails") != null) {
                      
              if (response.get("cardDetails.cardNumber") != null) {
                  
                MatcherAssert.assertThat(response.get("cardDetails.cardNumber"), instanceOf(String.class));
              }
      
              if (response.get("cardDetails.expiryDate") != null) {
                  
                MatcherAssert.assertThat(response.get("cardDetails.expiryDate"), instanceOf(String.class));
              }
      
              if (response.get("cardDetails.cvv") != null) {
                  
                MatcherAssert.assertThat(response.get("cardDetails.cvv"), instanceOf(String.class));
              }
      
              if (response.get("cardDetails.pin") != null) {
                  
                MatcherAssert.assertThat(response.get("cardDetails.pin"), instanceOf(String.class));
              }

              }
      
              if (response.get("personalQuestions") != null) {
                      
              if (response.get("personalQuestions.DOB") != null) {
                  
                MatcherAssert.assertThat(response.get("personalQuestions.DOB"), instanceOf(String.class));
              }
      
              if (response.get("personalQuestions.SSN") != null) {
                  
                MatcherAssert.assertThat(response.get("personalQuestions.SSN"), instanceOf(Integer.class));
              }
      
              if (response.get("personalQuestions.SecretPassword") != null) {
                  
                MatcherAssert.assertThat(response.get("personalQuestions.SecretPassword"), instanceOf(String.class));
              }
      
              if (response.get("personalQuestions.LDAmount") != null) {
                  
                MatcherAssert.assertThat(response.get("personalQuestions.LDAmount"), instanceOf(Integer.class));
              }
      
              if (response.get("personalQuestions.AccNumber") != null) {
                  
                MatcherAssert.assertThat(response.get("personalQuestions.AccNumber"), instanceOf(String.class));
              }

              }
      
              if (response.get("ssNumber") != null) {
                  
                MatcherAssert.assertThat(response.get("ssNumber"), instanceOf(Integer.class));
              }
      
              if (response.get("ssnShort") != null) {
                  
                MatcherAssert.assertThat(response.get("ssnShort"), instanceOf(Integer.class));
              }
      
              if (response.get("alternatePhoneNumber") != null) {
                  
                MatcherAssert.assertThat(response.get("alternatePhoneNumber"), instanceOf(Integer.class));
              }
      
              if (response.get("customerId") != null) {
                  
                MatcherAssert.assertThat(response.get("customerId"), instanceOf(String.class));
              }
      
              if (response.get("email") != null) {
                  
                MatcherAssert.assertThat(response.get("email"), instanceOf(String.class));
              }
      
              if (response.get("identificationNumber") != null) {
                  
                MatcherAssert.assertThat(response.get("identificationNumber"), instanceOf(String.class));
              }
      
              if (response.get("identificationType") != null) {
                  
                MatcherAssert.assertThat(response.get("identificationType"), instanceOf(String.class));
              }
      
              if (response.get("image") != null) {
                  
                MatcherAssert.assertThat(response.get("image"), instanceOf(String.class));
              }
      
              if (response.get("isAlternateMobileNumber") != null) {
                  
                MatcherAssert.assertThat(response.get("isAlternateMobileNumber"), instanceOf(Boolean.class));
              }
      
              if (response.get("isPrimaryMobileNumber") != null) {
                  
                MatcherAssert.assertThat(response.get("isPrimaryMobileNumber"), instanceOf(Boolean.class));
              }
      
              if (response.get("location") != null) {
                  
                MatcherAssert.assertThat(response.get("location"), instanceOf(String.class));
              }
      
              if (response.get("name") != null) {
                  
                MatcherAssert.assertThat(response.get("name"), instanceOf(String.class));
              }
      
              if (response.get("personalBanker") != null) {
                      
              if (response.get("personalBanker.name") != null) {
                  
                MatcherAssert.assertThat(response.get("personalBanker.name"), instanceOf(String.class));
              }
      
              if (response.get("personalBanker.email") != null) {
                  
                MatcherAssert.assertThat(response.get("personalBanker.email"), instanceOf(String.class));
              }
      
              if (response.get("personalBanker.mobileNumber") != null) {
                  
                MatcherAssert.assertThat(response.get("personalBanker.mobileNumber"), instanceOf(String.class));
              }

              }
      
              if (response.get("phone") != null) {
                  
                MatcherAssert.assertThat(response.get("phone"), instanceOf(Integer.class));
              }
      
              if (response.get("securityQuestions") != null) {
                      
                for (int i = 0; i < response.getList("securityQuestions").size(); i++) {      
                  }    
                MatcherAssert.assertThat(response.getList("securityQuestions"), instanceOf(List.class));

              }
      
              if (response.get("segmentId") != null) {
                  
                MatcherAssert.assertThat(response.get("segmentId"), instanceOf(Integer.class));
              }
      
              if (response.get("multiAccounts") != null) {
                        
                  for (int i = 0; i < response.getList("multiAccounts").size(); i++) {      
              if (response.get("multiAccounts["+ i +"].accountNumber") != null) {
                  
                MatcherAssert.assertThat(response.get("multiAccounts["+ i +"].accountNumber"), instanceOf(String.class));
              }
      
              if (response.get("multiAccounts["+ i +"].cardDetails") != null) {
                      
              if (response.get("multiAccounts["+ i +"].cardDetails.cardNumber") != null) {
                  
                MatcherAssert.assertThat(response.get("multiAccounts["+ i +"].cardDetails.cardNumber"), instanceOf(String.class));
              }
      
              if (response.get("multiAccounts["+ i +"].cardDetails.expiryDate") != null) {
                  
                MatcherAssert.assertThat(response.get("multiAccounts["+ i +"].cardDetails.expiryDate"), instanceOf(String.class));
              }
      
              if (response.get("multiAccounts["+ i +"].cardDetails.cvv") != null) {
                  
                MatcherAssert.assertThat(response.get("multiAccounts["+ i +"].cardDetails.cvv"), instanceOf(String.class));
              }
      
              if (response.get("multiAccounts["+ i +"].cardDetails.pin") != null) {
                  
                MatcherAssert.assertThat(response.get("multiAccounts["+ i +"].cardDetails.pin"), instanceOf(String.class));
              }

              }
      
              if (response.get("multiAccounts["+ i +"].personalQuestions") != null) {
                      
              if (response.get("multiAccounts["+ i +"].personalQuestions.DOB") != null) {
                  
                MatcherAssert.assertThat(response.get("multiAccounts["+ i +"].personalQuestions.DOB"), instanceOf(String.class));
              }
      
              if (response.get("multiAccounts["+ i +"].personalQuestions.SSN") != null) {
                  
                MatcherAssert.assertThat(response.get("multiAccounts["+ i +"].personalQuestions.SSN"), instanceOf(Integer.class));
              }
      
              if (response.get("multiAccounts["+ i +"].personalQuestions.SecretPassword") != null) {
                  
                MatcherAssert.assertThat(response.get("multiAccounts["+ i +"].personalQuestions.SecretPassword"), instanceOf(String.class));
              }
      
              if (response.get("multiAccounts["+ i +"].personalQuestions.LDAmount") != null) {
                  
                MatcherAssert.assertThat(response.get("multiAccounts["+ i +"].personalQuestions.LDAmount"), instanceOf(Integer.class));
              }
      
              if (response.get("multiAccounts["+ i +"].personalQuestions.AccNumber") != null) {
                  
                MatcherAssert.assertThat(response.get("multiAccounts["+ i +"].personalQuestions.AccNumber"), instanceOf(String.class));
              }

              }
      
              if (response.get("multiAccounts["+ i +"].ssNumber") != null) {
                  
                MatcherAssert.assertThat(response.get("multiAccounts["+ i +"].ssNumber"), instanceOf(Integer.class));
              }
      
              if (response.get("multiAccounts["+ i +"].ssnShort") != null) {
                  
                MatcherAssert.assertThat(response.get("multiAccounts["+ i +"].ssnShort"), instanceOf(Integer.class));
              }
      
              if (response.get("multiAccounts["+ i +"].alternatePhoneNumber") != null) {
                  
                MatcherAssert.assertThat(response.get("multiAccounts["+ i +"].alternatePhoneNumber"), instanceOf(Integer.class));
              }
      
              if (response.get("multiAccounts["+ i +"].customerId") != null) {
                  
                MatcherAssert.assertThat(response.get("multiAccounts["+ i +"].customerId"), instanceOf(String.class));
              }
      
              if (response.get("multiAccounts["+ i +"].email") != null) {
                  
                MatcherAssert.assertThat(response.get("multiAccounts["+ i +"].email"), instanceOf(String.class));
              }
      
              if (response.get("multiAccounts["+ i +"].identificationNumber") != null) {
                  
                MatcherAssert.assertThat(response.get("multiAccounts["+ i +"].identificationNumber"), instanceOf(String.class));
              }
      
              if (response.get("multiAccounts["+ i +"].identificationType") != null) {
                  
                MatcherAssert.assertThat(response.get("multiAccounts["+ i +"].identificationType"), instanceOf(String.class));
              }
      
              if (response.get("multiAccounts["+ i +"].location") != null) {
                  
                MatcherAssert.assertThat(response.get("multiAccounts["+ i +"].location"), instanceOf(String.class));
              }
      
              if (response.get("multiAccounts["+ i +"].name") != null) {
                  
                MatcherAssert.assertThat(response.get("multiAccounts["+ i +"].name"), instanceOf(String.class));
              }
      
              if (response.get("multiAccounts["+ i +"].phone") != null) {
                  
                MatcherAssert.assertThat(response.get("multiAccounts["+ i +"].phone"), instanceOf(Integer.class));
              }
        
                    }    
                MatcherAssert.assertThat(response.getList("multiAccounts"), instanceOf(List.class));

              }
      
              if (response.get("warningCodes") != null) {
                        
                  for (int i = 0; i < response.getList("warningCodes").size(); i++) {      
              if (response.get("warningCodes["+ i +"].code") != null) {
                  
                MatcherAssert.assertThat(response.get("warningCodes["+ i +"].code"), instanceOf(Integer.class));
              }
      
              if (response.get("warningCodes["+ i +"].level") != null) {
                  
                MatcherAssert.assertThat(response.get("warningCodes["+ i +"].level"), instanceOf(String.class));
              }
      
              if (response.get("warningCodes["+ i +"].description") != null) {
                  
                MatcherAssert.assertThat(response.get("warningCodes["+ i +"].description"), instanceOf(String.class));
              }
        
                    }    
                MatcherAssert.assertThat(response.getList("warningCodes"), instanceOf(List.class));

              }
				}
if(stringifiedStatusCode.equals("401")){					System.out.println("Description: Error: Authorisation failed.");
      
              if (response.get("err") != null) {
                      
              if (response.get("err.message") != null) {
                  
                MatcherAssert.assertThat(response.get("err.message"), instanceOf(String.class));
              }

              }
				}
if(stringifiedStatusCode.equals("404")){					System.out.println("Description: Error: Not Found");
      
              if (response.get("err") != null) {
                      
              if (response.get("err.message") != null) {
                  
                MatcherAssert.assertThat(response.get("err.message"), instanceOf(String.class));
              }

              }
				}


            }  
    }
}
