// ********RoostGPT********
/*
Test generated by RoostGPT for test restAssuredJsonTest using AI Type Azure Open AI and AI Model roostgpt-4-32k

Test generated for /personalInfoValidation_post for http method type POST in rest-assured framework

RoostTestHash=abee211b9e

[
  {
    "ScenarioID": "1",
    "TestName": "testValidRequestReturns200",
    "Description": "Test making a valid request to the endpoint to ensure it returns 200",
    "Execution": {
      "Arrange": "Prepare a valid POST request with no parameters and correct headers",
      "Act": "Send POST request to /personalInfoValidation",
      "Assert": "Check for 200 status code"
    },
    "Validation": "Ensure API successfully returns a 200 response for valid input"
  },
  {
    "ScenarioID": "2",
    "TestName": "testUnauthorizedRequestReturns401",
    "Description": "Test request without valid authorization token to ensure it returns 401",
    "Execution": {
      "Arrange": "Prepare a POST request without an authorization token",
      "Act": "Send POST request to /personalInfoValidation",
      "Assert": "Check for 401 status code and error message in response body"
    },
    "Validation": "Ensure API handles authorization failure correctly"
  },
  {
    "ScenarioID": "3",
    "TestName": "testNotFoundRequestReturns404",
    "Description": "Test incorrect endpoint to verify API returns 404",
    "Execution": {
      "Arrange": "Prepare a POST request to a non-existent endpoint",
      "Act": "Send POST request to /personalInfoValidationInvalidPath",
      "Assert": "Check for 404 status code and error message in response body"
    },
    "Validation": "Ensure API correctly identifies and returns 404 for invalid paths"
  },
  {
    "ScenarioID": "4",
    "TestName": "testEmptyRequestBodyReturns200",
    "Description": "Test sending an empty body in the POST request to ensure validity",
    "Execution": {
      "Arrange": "Prepare an empty POST request body with proper headers",
      "Act": "Send POST request to /personalInfoValidation",
      "Assert": "Check for 200 status code"
    },
    "Validation": "Ensure API handles empty request body gracefully and returns success where applicable"
  },
  {
    "ScenarioID": "5",
    "TestName": "testInvalidRequestBodyFormatReturns400",
    "Description": "Test sending an invalid JSON format in the request body",
    "Execution": {
      "Arrange": "Prepare a POST request with a malformed JSON body",
      "Act": "Send POST request to /personalInfoValidation",
      "Assert": "Check for a 400 status code and an appropriate error message"
    },
    "Validation": "Ensure API rejects malformed JSON inputs and returns proper error"
  },
  {
    "ScenarioID": "6",
    "TestName": "testNullRequestBodyReturns200",
    "Description": "Test sending a null body to verify API behavior",
    "Execution": {
      "Arrange": "Prepare a POST request with a null request body and proper headers",
      "Act": "Send POST request to /personalInfoValidation",
      "Assert": "Check for 200 status code"
    },
    "Validation": "Ensure API handles null request body gracefully"
  },
  {
    "ScenarioID": "7",
    "TestName": "testMissingContentTypeHeaderReturns400",
    "Description": "Test request with missing Content-Type header to verify API behavior",
    "Execution": {
      "Arrange": "Prepare a POST request without Content-Type header",
      "Act": "Send POST request to /personalInfoValidation",
      "Assert": "Check for 400 status code and an appropriate error message"
    },
    "Validation": "Ensure API properly validates essential headers and returns error for missing Content-Type"
  },
  {
    "ScenarioID": "8",
    "TestName": "testUnsupportedHTTPMethodReturns405",
    "Description": "Test using unsupported HTTP method to ensure API responds correctly",
    "Execution": {
      "Arrange": "Prepare a GET request to /personalInfoValidation endpoint",
      "Act": "Send GET request to /personalInfoValidation",
      "Assert": "Check for 405 status code"
    },
    "Validation": "Ensure API only allows supported HTTP methods and rejects unsupported ones"
  },
  {
    "ScenarioID": "9",
    "TestName": "testRequestWithExtraHeadersReturns200",
    "Description": "Test adding unnecessary headers in the request to verify robustness",
    "Execution": {
      "Arrange": "Prepare a POST request with extra headers alongside valid headers",
      "Act": "Send POST request to /personalInfoValidation",
      "Assert": "Check for 200 status code"
    },
    "Validation": "Ensure API can accept requests with additional headers without failures"
  },
  {
    "ScenarioID": "10",
    "TestName": "testMalformedURIEncodingReturns404",
    "Description": "Test sending a request with malformed URI path to verify correct response",
    "Execution": {
      "Arrange": "Prepare a POST request to /personalInfoVal%20idation",
      "Act": "Send POST request to /personalInfoVal%20idation",
      "Assert": "Check for 404 status code and error message"
    },
    "Validation": "Ensure API correctly identifies malformed URIs and returns proper error"
  }
]

*/

// ********RoostGPT********
package org.springframework.RoostTest;

import org.json.JSONObject;
import org.json.JSONArray;
import io.restassured.RestAssured;
import io.restassured.response.Response;
import io.restassured.path.json.JsonPath;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import java.util.*;
import static io.restassured.RestAssured.given;
import static org.hamcrest.Matchers.*;
import org.hamcrest.MatcherAssert;

public class PersonalInfoValidationPostTest {

    List<JSONObject> testCases = new ArrayList<>();

    @BeforeEach
    public void setUp() {
        TestdataLoader dataloader = new TestdataLoader();
        testCases = dataloader.loadJson("src/test/java/org/springframework/RoostTest/personalInfoValidationPostTest.JSON");
    }


    @Test
    public void PersonalInfoValidationPost_Test() {
        this.setUp();
        Integer testNumber = 1;
        for (JSONObject testData : testCases) {
            RestAssured.baseURI = "https://localhost:8080/smt";

            JSONObject requestHeader = testData.optJSONObject("request_header");
            JSONObject requestBody = testData.optJSONObject("request_body");
            JSONObject queryParams = testData.optJSONObject("query_params");
            JSONObject pathParams = testData.optJSONObject("path_params");
            String requestPath = "/personalInfoValidation";

            if (pathParams != null) {
                for (String key : pathParams.keySet()) {
                    requestPath = requestPath.replace("{" + key + "}", pathParams.getString(key));
                }
            }

            io.restassured.specification.RequestSpecification req = given();

            // Resolve Authorization token priority: ENV > Param(RoostENV) > JSON
            String userEnvAuthToken = System.getenv("AUTH_TOKEN");
            String resolvedAuthToken = (userEnvAuthToken != null && !userEnvAuthToken.isEmpty()) ? userEnvAuthToken : "credential-register/swagger_server/swagger/swagger.yaml";

            boolean authSet = false;
            if (requestHeader != null) {
                Iterator<String> keys = requestHeader.keys();
                while (keys.hasNext()) {
                    String key = keys.next();
                    String value = requestHeader.getString(key);

                    if (key.equalsIgnoreCase("Authorization")) {
                        if (value.equalsIgnoreCase("${AUTH_TOKEN}") && resolvedAuthToken != null && !resolvedAuthToken.isEmpty()) {
                            req.header("Authorization", "Bearer " + resolvedAuthToken);
                            authSet = true;
                        } else {
                            req.header(key, value);
                            authSet = true;
                        }
                    } else {
                        req.header(key, value);
                    }
                }
            }

            if (!authSet && resolvedAuthToken != null && !resolvedAuthToken.isEmpty()) {
                req.header("Authorization", "Bearer " + resolvedAuthToken);
            }

            if (queryParams != null) {
                for (String key : queryParams.keySet()) {
                    req.queryParam(key, queryParams.get(key));
                }
            }

            if (requestBody != null && requestBody.length() > 0) {
                req.body(requestBody.toString());
            }

            Response responseObj;
            switch ("post".toLowerCase()) {
              case "post":
                responseObj = req.when().post(requestPath);
                break;
              case "get":
                responseObj = req.when().get(requestPath);
                break;
              case "put":
                responseObj = req.when().put(requestPath);
                break;
              case "delete":
                responseObj = req.when().delete(requestPath);
                break;
              default:
                throw new RuntimeException("Unsupported HTTP method: " + "post");
            }

            responseObj = responseObj.then().extract().response();

            System.out.printf("Test Case %d: PersonalInfoValidationPost_Test\n", testNumber++);
            System.out.println("Request: POST " + requestPath);
            System.out.println("Status Code: " + responseObj.statusCode());

            if (testData.has("expected_status_code")) {
                int expectedCode = testData.getInt("expected_status_code");
                MatcherAssert.assertThat(
                    "Expected status code " + expectedCode + " but got " + responseObj.statusCode(),
                    responseObj.statusCode(),
                    equalTo(expectedCode)
                );
            }
        }
    }
}
