# ********RoostGPT********

# Test generated by RoostGPT for test pw-test-1746086822742 using AI Type Open AI and AI Model gpt-4
# 
# Feature file generated for /example_get for http method type GET 
# RoostTestHash=2d7889707c
# 
# 

# ********RoostGPT********
Feature: Server example operation

  Background:
    * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:4010')
    * url urlBase
    * configure headers = { Authorization: '#(karate.properties['AUTH_TOKEN'])' }

  Scenario: Test GET method for /example endpoint
    Given path '/example'
    When method get
    Then status 200
    And match response contains { description: '#string' }
