# ********RoostGPT********

# Test generated by RoostGPT for test weather_api_test using AI Type Open AI and AI Model gpt-4o
# 
# Feature file generated for /astronomy.json_get for http method type GET 
# RoostTestHash=656c29a7ca
# 
# 

# ********RoostGPT********
Feature: Astronomy API Tests

  Background:
    * def baseURL = karate.properties['WEATHER_API_BASE_URL'] || karate.properties['API_HOST']
    * url baseURL
    * def authToken = karate.properties['AUTH_TOKEN'] || karate.properties['key']
    * header Accept = 'application/json'

  Scenario Outline: Validate Astronomy API with valid parameters
    Given path '/v1/astronomy.json'
    And param key = authToken
    And param q = '<location>'
    And param dt = '<date>'
    When method GET
    Then status 200
    And match response.location.name == '#string'
    And match response.location.region == '#string'
    And match response.location.country == '#string'
    And match response.location.lat == '#number'
    And match response.location.lon == '#number'
    And match response.location.tz_id == '#string'
    And match response.location.localtime_epoch == '#number'
    And match response.location.localtime == '#string'
    And match response.astronomy.astro.sunrise == '#string'
    And match response.astronomy.astro.sunset == '#string'
    And match response.astronomy.astro.moonrise == '#string'
    And match response.astronomy.astro.moonset == '#string'
    And match response.astronomy.astro.moon_phase == '#string'
    And match response.astronomy.astro.moon_illumination == '#string'

    Examples:
      | location   | date       |
      | 'New York' | '2023-10-01' |
      | 'London'   | '2023-10-02' |

  Scenario: Validate Astronomy API with missing 'q' parameter
    Given path '/v1/astronomy.json'
    And param key = authToken
    And param dt = '2023-10-01'
    When method GET
    Then status 400
    And match response.code == 1003
    And match response.message == '#string'

  Scenario: Validate Astronomy API with invalid API key
    Given path '/v1/astronomy.json'
    And param key = 'invalid_key'
    And param q = 'New York'
    And param dt = '2023-10-01'
    When method GET
    Then status 401
    And match response.code == 2006
    And match response.message == '#string'

  Scenario: Validate Astronomy API with exceeded API key quota
    Given path '/v1/astronomy.json'
    And param key = authToken
    And param q = 'New York'
    And param dt = '2023-10-01'
    When method GET
    Then status 403
    And match response.code == 2007
    And match response.message == '#string'
