# ********RoostGPT********

# Test generated by RoostGPT for test pw-api-karate-github-azure-1778650173458 using AI Type Azure Open AI and AI Model gpt-4.1
# 
# Feature file generated for /example_get for http method type GET 
# RoostTestHash=2d7889707c
# 
# 

# ********RoostGPT********
Feature: Example Operation - /example Endpoint

  Background:
    * def baseURL = karate.properties['SAMPLE_APPLICATION_FLOW_OAUTH2_PROJECT_BASE_URL'] || karate.properties['API_HOST']
    * url baseURL
    * def authToken = karate.properties['AUTH_TOKEN'] || karate.properties['AUTH_TOKEN']
    * configure headers = { Accept: 'application/json', Authorization: '#(authToken)' }

  Scenario: Get /example returns 200 OK
    Given path '/example'
    When method get
    Then status 200
    And match response == '#? _ == null || typeof _ == "object"'
    And assert responseHeaders != null
    And match responseHeaders['Content-Type'] == '#? _ == null || typeof _ == "string"'
