# ********RoostGPT********

# Test generated by RoostGPT for test pw-api-karate-github-claude-1769167805809 using AI Type Claude AI and AI Model claude-sonnet-4-20250514
# 
# Feature file generated for /example_get for http method type GET 
# RoostTestHash=2d7889707c
# 
# 

# ********RoostGPT********
Feature: Server example operation

Background:
  * def baseURL = karate.properties['SAMPLE_APPLICATION_FLOW_OAUTH2_PROJECT_BASE_URL'] || karate.properties['SAMPLE_APPLICATION_FLOW_OAUTH2_PROJECT_BASE_URL']
  * url baseURL
  * def authToken = 'Bearer ' + karate.properties['AUTH_TOKEN'] || karate.properties['AUTH_TOKEN']
  * configure headers = { Authorization: '#(authToken)', Accept: 'application/json' }

Scenario: GET /example - Successful response
  Given path '/example'
  When method GET
  Then status 200

Scenario: GET /example - Verify response headers
  Given path '/example'
  When method GET
  Then status 200
  And match responseHeaders['Content-Type'] == '#present'

Scenario: GET /example - Invalid authorization
  Given path '/example'
  And configure headers = { Accept: 'application/json' }
  When method GET
  Then assert responseStatus != 200

Scenario: GET /example - Malformed authorization token
  Given path '/example'
  And configure headers = { Authorization: 'InvalidToken', Accept: 'application/json' }
  When method GET
  Then assert responseStatus != 200
