# ********RoostGPT********

# Test generated by RoostGPT for test KaratetTest using AI Type Open AI and AI Model gpt-4o
# 
# Feature file generated for /laureate/{laureateID}_get for http method type GET 
# RoostTestHash=3a8d014c99
# 
# 

# ********RoostGPT********
Feature: Test Nobel Prize Laureate API

  Background:
    * def baseURL = karate.properties['NOBEL_PRIZE_MASTER_DATA_BASE_URL'] || karate.properties['NOBEL_PRIZE_MASTER_DATA_BASE_URL']
    * url baseURL
    * configure headers = { Accept: 'application/json' }

  Scenario Outline: Validate Laureate Details with Valid ID
    Given path '/2.1/laureate/<laureateID>'
    When method GET
    Then status 200
    And match response.laureate.id == '#number'
    And match response.laureate.laureateIfPerson == '##object'
    And match response.laureate.laureateIfOrg == '##object'
    And match response.laureate.wikipedia == '##object'
    And match response.laureate.wikidata == '##object'
    And match response.laureate.sameAs == '##array'
    And match response.laureate.links == '##array'
    And match response.laureate.nobelPrizes == '##array'
    Examples:
      | laureateID |
      | 1          |
      | 456        |

  Scenario Outline: Validate Missing Resource with Invalid ID
    Given path '/2.1/laureate/<laureateID>'
    When method GET
    Then assert responseStatus == 404
    And match response.code == '#string'
    And match response.message == '#string'
    Examples:
      | laureateID |
      | 999999     |
      | -1         |

  Scenario Outline: Validate Bad Request with Malformed ID
    Given path '/2.1/laureate/<laureateID>'
    When method GET
    Then assert responseStatus == 400
    And match response.code == '#string'
    And match response.message == '#string'
    Examples:
      | laureateID |
      | 'abc'      |
      | ''         |

  Scenario Outline: Validate Unprocessable Entity
    Given path '/2.1/laureate/<laureateID>'
    When method GET
    Then assert responseStatus == 422
    And match response.code == '#string'
    And match response.message == '#string'
    Examples:
      | laureateID |
      | 0          |
      | -100       |
