# ********RoostGPT********

# Test generated by RoostGPT for test Exi-PW-Karate-VertexAi using AI Type Vertex AI and AI Model claude-3-7-sonnet
# 
# Feature file generated for /laureate/{laureateID}_get for http method type GET 
# RoostTestHash=4d779ed43d
# 
# 

# ********RoostGPT********
Feature: Laureate API Endpoint

  Background:
    * def baseURL = karate.properties['NOBEL_PRIZE_MASTER_DATA_BASE_URL'] || karate.properties['API_HOST']
    * url baseURL
    * configure report = true
    * header Accept = 'application/json'

  Scenario Outline: Get laureate details with valid laureateID
    Given path '/2.1/laureate/<laureateID>'
    When method GET
    Then status 200
    And match response == '#object'

    Examples:
      | read('laureate_laureateID_get.csv') |

  Scenario Outline: Get laureate with invalid laureateID format
    Given path '/2.1/laureate/<laureateID>'
    When method GET
    Then status 400
    And match response.code == '#string'
    And match response.message == '#string'

    Examples:
      | laureateID |
      | 'abc'      |
      |         -1 |
      |          0 |

  Scenario Outline: Get laureate with non-existent laureateID
    Given path '/2.1/laureate/<laureateID>'
    When method GET
    Then status 404
    And match response.code == '#string'
    And match response.message == '#string'

    Examples:
      | laureateID |
      |      99999 |
      |     100000 |

  Scenario Outline: Get laureate with unprocessable laureateID
    Given path '/2.1/laureate/<laureateID>'
    When method GET
    Then status 422
    And match response.code == '#string'
    And match response.message == '#string'

    Examples:
      | laureateID |
      | 2147483648 |
