# ********RoostGPT********

# Test generated by RoostGPT for test KaratetTest using AI Type Open AI and AI Model gpt-4o
# 
# Feature file generated for /nobelPrize/{category}/{year}_get for http method type GET 
# RoostTestHash=adfce3f1d2
# 
# 

# ********RoostGPT********
Feature: Nobel Prize API Tests

  Background:
    * def baseURL = karate.properties['NOBEL_PRIZE_MASTER_DATA_BASE_URL'] || karate.properties['NOBEL_PRIZE_MASTER_DATA_BASE_URL']
    * url baseURL
    * header Accept = 'application/json'

  Scenario Outline: Validate Nobel Prize API with valid category and year
    Given path '2.1', 'nobelPrize', '<category>', '<year>'
    When method GET
    Then status 200
    And match response.nobelPrize == '#object'
    And match response.nobelPrize.awardYear == '#number'
    And match response.nobelPrize.category.en == '#string'
    And match response.nobelPrize.category.se == '#string'
    And match response.nobelPrize.category.false == '#string'
    And match response.nobelPrize.categoryFullName.en == '#string'
    And match response.nobelPrize.categoryFullName.se == '#string'
    And match response.nobelPrize.categoryFullName.false == '#string'
    And match response.nobelPrize.dateAwarded == '#string'
    And match response.nobelPrize.prizeAmount == '#number'
    And match response.nobelPrize.prizeAmountAdjusted == '#number'
    And match response.nobelPrize.topMotivation.en == '#string'
    And match response.nobelPrize.topMotivation.se == '#string'
    And match response.nobelPrize.topMotivation.false == '#string'
    And match response.nobelPrize.laureates == '#array'
    And match each response.nobelPrize.laureates[*].id == '#number'
    And match each response.nobelPrize.laureates[*].name.en == '#string'
    And match each response.nobelPrize.laureates[*].name.se == '#string'
    And match each response.nobelPrize.laureates[*].name.false == '#string'
    And match each response.nobelPrize.laureates[*].portion == '#string'
    And match each response.nobelPrize.laureates[*].sortOrder == '#string'
    And match each response.nobelPrize.laureates[*].motivation.en == '#string'
    And match each response.nobelPrize.laureates[*].motivation.se == '#string'
    And match each response.nobelPrize.laureates[*].motivation.false == '#string'
    And match each response.nobelPrize.laureates[*].links == '#array'
    And match each response.nobelPrize.laureates[*].links[*].rel == '#string'
    And match each response.nobelPrize.laureates[*].links[*].href == '#string'
    And match each response.nobelPrize.laureates[*].links[*].action == '#string'
    And match each response.nobelPrize.laureates[*].links[*].types == '#string'
    
    Examples:
      | category | year |
      | 'che'    | 1989 |
      | 'eco'    | 1990 |

  Scenario Outline: Validate Nobel Prize API with invalid category or year
    Given path '2.1', 'nobelPrize', '<category>', '<year>'
    When method GET
    Then assert responseStatus != 200
    And match response.code == '#string'
    And match response.message == '#string'

    Examples:
      | category | year |
      | 'xyz'    | 1989 |
      | 'che'    | 1899 |
      | 'lit'    | 2050 |

  Scenario: Validate Nobel Prize API with unsupported HTTP method
    Given path '2.1', 'nobelPrize', 'che', '1989'
    When method POST
    Then assert responseStatus != 200
    And match response.code == '#string'
    And match response.message == '#string'
