# ********RoostGPT********

# Test generated by RoostGPT for test KaratetTest using AI Type Open AI and AI Model gpt-4o
# 
# Feature file generated for /employees_post for http method type POST 
# RoostTestHash=b517afeac4
# 
# 

# ********RoostGPT********
Feature: Employee API Tests

  Background:
    * def urlBase = karate.properties['API_HOST']
    * url urlBase

  Scenario Outline: Add Employee - Valid Input
    Given path 'employees'
    And request
      """
      { 
        "name": "<name>", 
        "email": "<email>", 
        "jobTitle": "<jobTitle>" 
      }
      """
    When method POST
    Then status 201
    And match response == '#null'
    And match responseHeaders['Content-Type'] contains 'application/json'

    Examples:
      | read('employees_post.csv') |

  Scenario Outline: Add Employee - Invalid Input
    Given path 'employees'
    And request
      """
      { 
        "name": "<name>", 
        "email": "<email>", 
        "jobTitle": "<jobTitle>" 
      }
      """
    When method POST
    Then status 400
    And match response == '#null'
    And match responseHeaders['Content-Type'] contains 'application/json'

    Examples:
      | name | email | jobTitle |
      |      |       |          |

  Scenario Outline: Add Employee - Duplicate Entry
    Given path 'employees'
    And request
      """
      { 
        "name": "<name>", 
        "email": "<email>", 
        "jobTitle": "<jobTitle>" 
      }
      """
    When method POST
    Then status 409
    And match response == '#null'
    And match responseHeaders['Content-Type'] contains 'application/json'

    Examples:
      | name       | email                    | jobTitle       |
      | John Smith | john.smith@acme-corp.com | System Analyst |
