# ********RoostGPT********

# Test generated by RoostGPT for test APITEST_pytest using AI Type Open AI and AI Model gpt-4o
# 
# Test file generated for /forecast.json_get for http method type GET 
# RoostTestHash=2d002b4f8c
# 
# 

# ********RoostGPT********
"""
Pytest test suite for the Weather API's forecast endpoint.

To execute these tests, run `pytest` in the terminal.
Ensure that the conftest.py and config.yml are correctly set up.
"""

import pytest
from pathlib import Path
from validator import SwaggerSchemaValidator

_ENDPOINT = "/v1/forecast.json"
_METHOD = "get"
_TEST_DATA_FILE = "forecast_json.json"
_here = Path(__file__).resolve().parent
_endpoint_data_path = _here / _TEST_DATA_FILE

@pytest.mark.smoke
def test_forecast_endpoint(api_client, config, merged_test_data):
    validator = SwaggerSchemaValidator(str(_here / "api.json"))
    data = merged_test_data(_endpoint_data_path)

    for test_case in data:
        params = {
            "q": test_case.get("q"),
            "days": test_case.get("days"),
            "lang": test_case.get("lang", None),
            "alerts": test_case.get("alerts", None),
            "aqi": test_case.get("aqi", None),
        }
        params = {k: v for k, v in params.items() if v is not None}

        headers = {
            "Authorization": f"Bearer {config['auth']['ApiKeyAuth']}"
        }

        response = api_client.get(_ENDPOINT, headers=headers, params=params)
        assert response.status_code == test_case["statusCode"], f"Expected {test_case['statusCode']}, got {response.status_code}"

        validation_result = validator.validate_schema_by_response(_ENDPOINT, _METHOD, response.status_code, response)
        assert validation_result["valid"], f"Response validation failed: {validation_result.get('message')}"

def test_forecast_endpoint_invalid_auth(api_client, merged_test_data):
    data = merged_test_data(_endpoint_data_path)

    for test_case in data:
        params = {
            "q": test_case.get("q"),
            "days": test_case.get("days"),
        }
        headers = {
            "Authorization": "Bearer invalid_token"
        }

        response = api_client.get(_ENDPOINT, headers=headers, params=params)
        assert response.status_code == 401, f"Expected 401, got {response.status_code}"

def test_forecast_endpoint_missing_auth(api_client, merged_test_data):
    data = merged_test_data(_endpoint_data_path)

    for test_case in data:
        params = {
            "q": test_case.get("q"),
            "days": test_case.get("days"),
        }

        response = api_client.get(_ENDPOINT, params=params)
        assert response.status_code == 401, f"Expected 401, got {response.status_code}"
